In [1]:
import pandas as pd
import requests

In [2]:
movies = pd.DataFrame()

In [3]:
for i in range(1,501):
    headers = {"accept": "application/json","Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNzJhZmMwNjQ2NzU5N2FkY2QwMTE0YjFkYWQwZDBiMCIsInN1YiI6IjYyZGQ0NmQxZWE4NGM3MDA2NzRhYTU1ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.10QUa8JMYbIZ1ljSPJF-sXfe389uc5Hpck-J8laFen4"}
    response = requests.get("https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={}".format(i), headers=headers)
    movies = movies.append(response.json()['results'], ignore_index=True)

In [4]:
movies_new = movies[['id','title','overview']]

In [5]:
movies_new

,id,title,overview
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
...,...,...,...
9995,124459,The Incredible Burt Wonderstone,After breaking up with his longtime stage part...
9996,523931,Megalodon,A military vessel on the search for an unident...
9997,265208,Wild Card,When a Las Vegas bodyguard with lethal skills ...
9998,51170,Open Season 3,"Boog, Elliot, and their forest friends return ..."
9999,39451,Little Fockers,"It has taken 10 years, two little Fockers with..."

In [6]:
movies_id = movies_new['id'].values.tolist()
movies_id

[238,
 278,
 240,
 424,
 19404,
 129,
 389,
 372058,
 496243,
 155,
 497,
 680,
 13,
 122,
 429,
 769,
 11216,
 346,
 637,
 12477,
 696374,
 772071,
 569094,
 539,
 550,
 620249,
 372754,
 311,
 704264,
 724089,
 667257,
 598,
 14537,
 510,
 761053,
 157336,
 820067,
 324857,
 4935,
 120,
 378064,
 40096,
 1891,
 255709,
 568332,
 121,
 423,
 244786,
 92321,
 995133,
 807,
 27205,
 567,
 599,
 73,
 18491,
 12493,
 652837,
 3782,
 274,
 914,
 128,
 533514,
 644479,
 872585,
 15804,
 101,
 207,
 105,
 851644,
 901,
 795607,
 630566,
 25237,
 283566,
 447362,
 16672,
 3082,
 335,
 20334,
 527641,
 29259,
 10494,
 28,
 975,
 637920,
 77338,
 315162,
 897429,
 361743,
 10376,
 670,
 632632,
 299534,
 618344,
 568300,
 265177,
 1585,
 441130,
 537061,
 299536,
 635302,
 8587,
 667276,
 508965,
 504253,
 572154,
 42269,
 290098,
 490132,
 797,
 24188,
 110420,
 5156,
 556574,
 354912,
 522924,
 694,
 37257,
 610892,
 284,
 575813,
 16869,
 185,
 476292,
 18148,
 31414,
 857,
 98,
 490,
 603,
 11,
 791373,
 1124,
 50014,
 11324,
 518068,
 324786,
 592350,
 133919,
 1398,
 629,
 10098,
 77,
 26451,
 555604,
 20532,
 1010581,
 823754,
 755812,
 313106,
 531428,
 426,
 517814,
 422,
 654299,
 626332,
 810693,
 606856,
 475557,
 68718,
 289,
 399106,
 398818,
 2457,
 1422,
 872,
 678512,
 470044,
 762975,
 111,
 664767,
 620683,
 103,
 600354,
 406997,
 19,
 20914,
 508442,
 297610,
 489,
 92060,
 666,
 532067,
 614,
 348,
 55823,
 439,
 20941,
 705,
 996,
 600,
 500,
 640344,
 37165,
 935,
 11878,
 550776,
 100,
 458220,
 411088,
 548,
 81481,
 9702,
 472454,
 239,
 895,
 21634,
 24382,
 12445,
 843,
 831827,
 400608,
 397567,
 38288,
 149871,
 832,
 38,
 46738,
 992,
 280,
 3780,
 103663,
 740937,
 347688,
 571265,
 146233,
 7345,
 655,
 526702,
 359940,
 406,
 387,
 334543,
 118662,
 62,
 4348,
 638507,
 8422,
 447365,
 51482,
 10681,
 785534,
 893941,
 11645,
 8392,
 17663,
 437068,
 147,
 678580,
 337404,
 53210,
 11423,
 42229,
 11659,
 800,
 381284,
 7347,
 610461,
 663558,
 1955,
 538362,
 120467,
 55960,
 515001,
 780,
 449176,
 529531,
 400928,
 26022,
 582,
 310569,
 9764,
 1091,
 106646,
 821,
 279,
 264644,
 5801,
 641,
 615457,
 339877,
 20530,
 204,
 522518,
 115929,
 19426,
 282848,
 673,
 521,
 307,
 14,
 574074,
 496450,
 9277,
 378108,
 37793,
 938,
 429210,
 31217,
 12761,
 962,
 15,
 568160,
 110416,
 31439,
 455661,
 11104,
 1396,
 524,
 359724,
 315465,
 205596,
 28178,
 3175,
 554596,
 595,
 28978,
 11778,
 140420,
 424694,
 58007,
 13223,
 28422,
 634649,
 25376,
 19542,
 3090,
 714888,
 785084,
 530915,
 20453,
 213,
 2517,
 488623,
 18438,
 11658,
 285700,
 652722,
 43949,
 14696,
 12104,
 961,
 776503,
 962232,
 29264,
 7508,
 38360,
 947,
 15383,
 560066,
 76,
 482321,
 426618,
 550205,
 1059,
 770,
 24,
 640,
 414419,
 242828,
 862,
 627,
 45752,
 1580,
 38286,
 1578,
 20803,
 10515,
 70,
 1092,
 41050,
 11712,
 897,
 458302,
 15244,
 10238,
 234,
 522402,
 237791,
 10404,
 360814,
 158445,
 110,
 21334,
 775,
 149,
 654,
 3777,
 501929,
 315620,
 160885,
 28971,
 76203,
 14160,
 405,
 23282,
 745,
 11010,
 961323,
 920394,
 455714,
 5925,
 698201,
 491480,
 37797,
 329,
 20722,
 30017,
 552532,
 142061,
 698948,
 523781,
 152532,
 81,
 6977,
 78,
 579792,
 438695,
 197,
 615453,
 10242,
 610150,
 9323,
 613868,
 10386,
 6715,
 667520,
 679,
 31411,
 85,
 150540,
 296096,
 8290,
 10728,
 10674,
 829,
 671,
 183011,
 33,
 746957,
 47796,
 1083862,
 522212,
 505262,
 334533,
 49964,
 20271,
 1646,
 223,
 316029,
 17295,
 715931,
 3034,
 2011,
 570503,
 489412,
 20874,
 69335,
 7857,
 10997,
 698508,
 122906,
 118340,
 632322,
 527774,
 32085,
 194,
 949,
 594634,
 20875,
 1402,
 662,
 404378,
 331482,
 30060,
 7984,
 712454,
 752,
 60243,
 597,
 198,
 31442,
 3870,
 313369,
 25364,
 210577,
 48035,
 1892,
 503314,
 435129,
 13398,
 827,
 3112,
 938008,
 369557,
 11830,
 29455,
 585511,
 804,
 3083,
 726684,
 11036,
 843906,
 180147,
 393,
 24167,
 3078,
 833,
 721656,
 548544,
 430424,
 16,
 25538,
 508943,
 379170,
 52629,
 556901,
 579245,
 244001,
 275,
 83564,
 505192,
 354857,
 24238,
 631,
 381341,
 1394,
 301,
 445030,
 399174,
 152601,
 266856,
 43469,
 235,
 573164,
 665,
 2721,
 11049,
 265195,
 779047,
 776305,
 23160,
 391,
 406785,
 453,
 934,
 777,
 398924,
 94047,
 546554,
 20873,
 1162,
 22596,
 593,
 16859,
 2440,
 113,
 937278,
 14836,
 11293,
 1607,
 581,
 916224,
 16804,
 530254,
 22843,
 14574,
 613,
 185789,
 5511,
 89,
 564427,
 32480,
 58129,
 1675,
 115,
 9479,
 5924,
 152742,
 33320,
 200727,
 59440,
 50759,
 93,
 86000,
 71157,
 45523,
 10774,
 545611,
 293299,
 585,
 761898,
 359156,
 1018,
 968,
 6075,
 367412,
 31011,
 603692,
 596,
 15859,
 16390,
 56231,
 826,
 677638,
 650031,
 116322,
 136,
 22683,
 12,
 579974,
 805,
 801335,
 47931,
 21135,
 11953,
 887,
 80,
 263115,
 126319,
 30588,
 10775,
 674,
 26955,
 12903,
 11602,
 29452,
 5915,
 946,
 5000,
 335578,
 314365,
 24480,
 348892,
 25606,
 10191,
 726759,
 393559,
 4977,
 882569,
 113833,
 11656,
 2062,
 744114,
 80379,
 5961,
 303867,
 554590,
 705861,
 609242,
 49797,
 1280,
 142,
 107,
 29458,
 5544,
 11697,
 419478,
 762,
 262,
 479718,
 25253,
 5991,
 502356,
 438631,
 31056,
 22,
 423612,
 10193,
 597316,
 323272,
 52345,
 14069,
 11621,
 1366,
 277216,
 13042,
 502,
 375794,
 9421,
 84892,
 13855,
 29845,
 2118,
 553,
 141,
 10315,
 770254,
 336804,
 149870,
 144,
 582927,
 20126,
 901563,
 49026,
 1040148,
 1626,
 831223,
 32916,
 396,
 303,
 766507,
 602063,
 49687,
 1480,
 10757,
 929170,
 10227,
 562,
 9475,
 166428,
 12444,
 117,
 86837,
 587,
 169813,
 14282,
 724495,
 396535,
 143,
 696,
 486589,
 352173,
 851,
 27670,
 2108,
 380,
 17483,
 11005,
 873,
 531,
 1417,
 925,
 703,
 492188,
 317442,
 81401,
 575264,
 539517,
 506574,
 413594,
 49046,
 18079,
 435366,
 6844,
 583,
 1700,
 165,
 61979,
 428493,
 40662,
 841755,
 382591,
 14756,
 713776,
 573699,
 374473,
 22504,
 963,
 656563,
 581528,
 269149,
 322,
 804095,
 337960,
 792,
 553835,
 273248,
 16237,
 12496,
 11902,
 216,
 3114,
 502033,
 903,
 12491,
 10229,
 12429,
 525,
 72660,
 45269,
 16761,
 15916,
 843241,
 177572,
 357786,
 30018,
 27064,
 556984,
 12405,
 11220,
 1908,
 1027014,
 234200,
 123025,
 980,
 576920,
 10020,
 334,
 709629,
 25050,
 404,
 886396,
 508439,
 451945,
 614917,
 16052,
 9800,
 808,
 756999,
 317182,
 244063,
 48831,
 803700,
 508933,
 393729,
 359784,
 672,
 616584,
 282758,
 24160,
 211954,
 40619,
 653,
 336,
 990,
 27040,
 20123,
 205,
 221732,
 203217,
 9552,
 414906,
 28162,
 309,
 162,
 30959,
 965150,
 869626,
 5528,
 583083,
 573171,
 31589,
 632,
 537116,
 453191,
 96721,
 24428,
 15265,
 575452,
 28571,
 19026,
 15121,
 446159,
 369145,
 13151,
 993,
 297222,
 499,
 498249,
 13002,
 9806,
 8416,
 288,
 242582,
 24657,
 137182,
 767,
 33602,
 20544,
 5910,
 272,
 581577,
 167581,
 9023,
 8016,
 587272,
 13929,
 12516,
 597922,
 369299,
 22137,
 1040,
 22881,
 1633,
 83666,
 20139,
 4495,
 688,
 795514,
 371645,
 4480,
 845,
 238628,
 11898,
 675,
 28276,
 4808,
 1075,
 11299,
 11787,
 367735,
 13187,
 995,
 164,
 108,
 51822,
 14811,
 522627,
 25858,
 342470,
 51608,
 3763,
 247,
 730840,
 15794,
 444705,
 773,
 637649,
 286217,
 49992,
 28145,
 11474,
 10633,
 11482,
 1904,
 1587,
 68,
 128246,
 100402,
 399566,
 2433,
 82702,
 16306,
 567410,
 27053,
 2493,
 44214,
 1632,
 76600,
 891,
 589739,
 439058,
 401698,
 976,
 23832,
 158,
 11972,
 4497,
 99,
 759054,
 626872,
 426426,
 336808,
 14580,
 2204,
 265169,
 8358,
 676701,
 320007,
 110160,
 580175,
 981,
 4347,
 4235,
 1939,
 702,
 51533,
 578,
 877703,
 50531,
 12548,
 28580,
 8832,
 338729,
 37247,
 15137,
 1592,
 261,
 534780,
 227932,
 11362,
 672322,
 10835,
 471707,
 144288,
 466282,
 431693,
 51739,
 530079,
 15251,
 812,
 899405,
 9343,
 366170,
 1093,
 871,
 218,
 592807,
 ...]

In [7]:
movies_cast = pd.DataFrame()

In [8]:
for i in movies_id:
    headers = {"accept": "application/json","Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNzJhZmMwNjQ2NzU5N2FkY2QwMTE0YjFkYWQwZDBiMCIsInN1YiI6IjYyZGQ0NmQxZWE4NGM3MDA2NzRhYTU1ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.10QUa8JMYbIZ1ljSPJF-sXfe389uc5Hpck-J8laFen4"}
    response = requests.get("https://api.themoviedb.org/3/movie/{}/credits?language=en-US".format(i) ,headers=headers)
    data = [[i,response.json().get('cast')]]
    temp = pd.DataFrame(data,columns=['id','Actors'])
    movies_cast = movies_cast.append(temp,ignore_index=True)

In [9]:
movies_cast

          id                                             Actors
0        238  [{'adult': False, 'gender': 2, 'id': 3084, 'kn...
1        278  [{'adult': False, 'gender': 2, 'id': 504, 'kno...
2        240  [{'adult': False, 'gender': 2, 'id': 1158, 'kn...
3        424  [{'adult': False, 'gender': 2, 'id': 3896, 'kn...
4      19404  [{'adult': False, 'gender': 2, 'id': 35742, 'k...
...      ...                                                ...
9995  124459  [{'adult': False, 'gender': 2, 'id': 4495, 'kn...
9996  523931  [{'adult': False, 'gender': 2, 'id': 147, 'kno...
9997  265208  [{'adult': False, 'gender': 2, 'id': 976, 'kno...
9998   51170  [{'adult': False, 'gender': 2, 'id': 1239270, ...
9999   39451  [{'adult': False, 'gender': 2, 'id': 380, 'kno...

[10000 rows x 2 columns]

In [10]:
movies_cast['Actors'][2]

[{'adult': False,
  'gender': 2,
  'id': 1158,
  'known_for_department': 'Acting',
  'name': 'Al Pacino',
  'original_name': 'Al Pacino',
  'popularity': 34.104,
  'profile_path': '/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg',
  'cast_id': 8,
  'character': 'Don Michael Corleone',
  'credit_id': '52fe422bc3a36847f8009505',
  'order': 0},
 {'adult': False,
  'gender': 2,
  'id': 3087,
  'known_for_department': 'Acting',
  'name': 'Robert Duvall',
  'original_name': 'Robert Duvall',
  'popularity': 19.95,
  'profile_path': '/nLBIEvJDvSV0WhFv0bi7sU9tLyb.jpg',
  'cast_id': 9,
  'character': 'Tom Hagen',
  'credit_id': '52fe422bc3a36847f8009509',
  'order': 1},
 {'adult': False,
  'gender': 1,
  'id': 3092,
  'known_for_department': 'Acting',
  'name': 'Diane Keaton',
  'original_name': 'Diane Keaton',
  'popularity': 18.888,
  'profile_path': '/tnx7pJqisfAzvXOR5wHQsbnH9XH.jpg',
  'cast_id': 10,
  'character': 'Kay Corleone',
  'credit_id': '52fe422bc3a36847f800950d',
  'order': 2},
 {'adult': False,
  'gender': 2,
  'id': 380,
  'known_for_department': 'Acting',
  'name': 'Robert De Niro',
  'original_name': 'Robert De Niro',
  'popularity': 36.215,
  'profile_path': '/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg',
  'cast_id': 11,
  'character': 'Vito Corleone',
  'credit_id': '52fe422bc3a36847f8009511',
  'order': 3},
 {'adult': False,
  'gender': 2,
  'id': 3096,
  'known_for_department': 'Acting',
  'name': 'John Cazale',
  'original_name': 'John Cazale',
  'popularity': 7.062,
  'profile_path': '/41wXX1FBalyIuf5eaA4S43Y8IfZ.jpg',
  'cast_id': 12,
  'character': "Frederico 'Fredo' Corleone",
  'credit_id': '52fe422bc3a36847f8009515',
  'order': 4},
 {'adult': False,
  'gender': 1,
  'id': 3094,
  'known_for_department': 'Acting',
  'name': 'Talia Shire',
  'original_name': 'Talia Shire',
  'popularity': 19.175,
  'profile_path': '/due9MtmbvCMDd1aNveuMyjsaZ8W.jpg',
  'cast_id': 13,
  'character': "Constanzia 'Connie' Corleone",
  'credit_id': '52fe422bc3a36847f8009519',
  'order': 5},
 {'adult': False,
  'gender': 2,
  'id': 3171,
  'known_for_department': 'Acting',
  'name': 'Lee Strasberg',
  'original_name': 'Lee Strasberg',
  'popularity': 0.833,
  'profile_path': '/niSM7ejzddgaTcxjgJMYEFCr9Y2.jpg',
  'cast_id': 14,
  'character': 'Hyman Roth',
  'credit_id': '52fe422bc3a36847f800951d',
  'order': 6},
 {'adult': False,
  'gender': 2,
  'id': 3172,
  'known_for_department': 'Acting',
  'name': 'Michael V. Gazzo',
  'original_name': 'Michael V. Gazzo',
  'popularity': 5.633,
  'profile_path': '/cTY2Hlf6sIR9xLI95bBir7eI0N.jpg',
  'cast_id': 15,
  'character': 'Frank Pentangeli',
  'credit_id': '52fe422bc3a36847f8009521',
  'order': 7},
 {'adult': False,
  'gender': 2,
  'id': 3173,
  'known_for_department': 'Acting',
  'name': 'G. D. Spradlin',
  'original_name': 'G. D. Spradlin',
  'popularity': 3.007,
  'profile_path': '/pWNa9H3ABB3Ug9CwTfVNtHsCFjV.jpg',
  'cast_id': 16,
  'character': 'Senator Pat Geary',
  'credit_id': '52fe422bc3a36847f8009525',
  'order': 8},
 {'adult': False,
  'gender': 2,
  'id': 3174,
  'known_for_department': 'Acting',
  'name': 'Richard Bright',
  'original_name': 'Richard Bright',
  'popularity': 8.085,
  'profile_path': '/b1ak2kPYUwBAYgD1yi50tz8BZ7J.jpg',
  'cast_id': 17,
  'character': 'Al Neri',
  'credit_id': '52fe422bc3a36847f8009529',
  'order': 9},
 {'adult': False,
  'gender': 2,
  'id': 3281,
  'known_for_department': 'Acting',
  'name': 'Gastone Moschin',
  'original_name': 'Gastone Moschin',
  'popularity': 3.942,
  'profile_path': '/dU58seqJs1NDkNodjwCbGZg3nqT.jpg',
  'cast_id': 34,
  'character': 'Don Fanucci',
  'credit_id': '52fe422bc3a36847f8009589',
  'order': 10},
 {'adult': False,
  'gender': 2,
  'id': 1213795,
  'known_for_department': 'Acting',
  'name': 'Tom Rosqui',
  'original_name': 'Tom Rosqui',
  'popularity': 3.425,
  'profile_path': None,
  'cast_id': 49,
  'character': 'Rocco Lampone',
  'credit_id': '55c0e47a9251410f780020ba',
  'order': 11},
 {'adult': False,
  'gender': 2,
  'id': 9257,
  'known_for_department': 'Acting',
  'name': 'Bruno Kirby',
  'original_name': 'Bruno Kirby',
  'popularity': 12.839,
  'profile_path': '/bvpcrrthfJ5jNbJnDeqJMuuneQB.jpg',
  'cast_id': 37,
  'character': 'Young Clemenza',
  'credit_id': '52fe422bc3a36847f8009597',
  'order': 12},
 {'adult': False,
  'gender': 2,
  'id': 11480,
  'known_for_department': 'Acting',
  'name': 'Frank Sivero',
  'original_name': 'Frank Sivero',
  'popularity': 8.4,
  'profile_path': '/eqvhj0iNtcsN6EJhd21Goqi1DSq.jpg',
  'cast_id': 38,
  'character': 'Genco Abbandando',
  'credit_id': '52fe422bc3a36847f800959b',
  'order': 13},
 {'adult': False,
  'gender': 1,
  'id': 3279,
  'known_for_department': 'Acting',
  'name': 'Francesca De Sapio',
  'original_name': 'Francesca De Sapio',
  'popularity': 3.627,
  'profile_path': '/rS0GiI3tx2HWvhHPNMIEw1f332s.jpg',
  'cast_id': 32,
  'character': 'Young Mama Corleone',
  'credit_id': '52fe422bc3a36847f8009581',
  'order': 14},
 {'adult': False,
  'gender': 1,
  'id': 933716,
  'known_for_department': 'Acting',
  'name': 'Morgana King',
  'original_name': 'Morgana King',
  'popularity': 1.277,
  'profile_path': '/zPsFAqH4NXD7rMWl2Kj3rEyGrKj.jpg',
  'cast_id': 39,
  'character': 'Mama Corleone',
  'credit_id': '52fe422bc3a36847f800959f',
  'order': 15},
 {'adult': False,
  'gender': 1,
  'id': 15659,
  'known_for_department': 'Acting',
  'name': 'Marianna Hill',
  'original_name': 'Marianna Hill',
  'popularity': 9.915,
  'profile_path': '/2Exz1SqtPkbM0EkkAKOk6I5OTg6.jpg',
  'cast_id': 40,
  'character': 'Deanna Corleone',
  'credit_id': '52fe422bc3a36847f80095a3',
  'order': 16},
 {'adult': False,
  'gender': 2,
  'id': 14151,
  'known_for_department': 'Acting',
  'name': 'Leopoldo Trieste',
  'original_name': 'Leopoldo Trieste',
  'popularity': 6.939,
  'profile_path': '/rviagoREwu8GhuDKzju8rNoYuo1.jpg',
  'cast_id': 41,
  'character': 'Signor Roberto',
  'credit_id': '52fe422bc3a36847f80095a7',
  'order': 17},
 {'adult': False,
  'gender': 2,
  'id': 68186,
  'known_for_department': 'Acting',
  'name': 'Dominic Chianese',
  'original_name': 'Dominic Chianese',
  'popularity': 8.499,
  'profile_path': '/wJIybLAbVv6VEPFpZtpxRW26aq2.jpg',
  'cast_id': 42,
  'character': 'Johnny Ola',
  'credit_id': '52fe422bc3a36847f80095ab',
  'order': 18},
 {'adult': False,
  'gender': 2,
  'id': 99788,
  'known_for_department': 'Acting',
  'name': 'Amerigo Tot',
  'original_name': 'Amerigo Tot',
  'popularity': 1.776,
  'profile_path': '/typSNLyasFnAn0uAEJDcmk0SKTQ.jpg',
  'cast_id': 50,
  'character': "Michael's Bodyguard",
  'credit_id': '55c0e4d3c3a36823c9001c61',
  'order': 19},
 {'adult': False,
  'gender': 2,
  'id': 45363,
  'known_for_department': 'Acting',
  'name': 'Troy Donahue',
  'original_name': 'Troy Donahue',
  'popularity': 8.319,
  'profile_path': '/uA02pDqGnuISqTXmsmLMiNWcl8h.jpg',
  'cast_id': 51,
  'character': 'Merle Johnson',
  'credit_id': '55c0e511c3a36823f4001cdd',
  'order': 20},
 {'adult': False,
  'gender': 2,
  'id': 104504,
  'known_for_department': 'Acting',
  'name': 'John Aprea',
  'original_name': 'John Aprea',
  'popularity': 2.409,
  'profile_path': '/hZ8Wlv3WaRMqNrRtWZBkw4lcjJj.jpg',
  'cast_id': 52,
  'character': 'Young Tessio',
  'credit_id': '55c0e53d9251410ee7001da1',
  'order': 21},
 {'adult': False,
  'gender': 2,
  'id': 16525,
  'known_for_department': 'Acting',
  'name': 'Joe Spinell',
  'original_name': 'Joe Spinell',
  'popularity': 8.657,
  'profile_path': '/jiok99ZvHDOj51BBgio2qvum0Mb.jpg',
  'cast_id': 53,
  'character': "William 'Willie' Cicci",
  'credit_id': '55c0e566c3a3682379001ffb',
  'order': 22},
 {'adult': False,
  'gender': 2,
  'id': 3093,
  'known_for_department': 'Acting',
  'name': 'Abe Vigoda',
  'original_name': 'Abe Vigoda',
  'popularity': 8.541,
  'profile_path': '/luWKPNb58IgJ2ovrtgPAzHGLLYL.jpg',
  'cast_id': 54,
  'character': "Salvatore 'Sal' Tessio",
  'credit_id': '55c0e5879251410ee7001dab',
  'order': 23},
 {'adult': False,
  'gender': 1,
  'id': 982089,
  'known_for_department': 'Acting',
  'name': 'Tere Livrano',
  'original_name': 'Tere Livrano',
  'popularity': 2.526,
  'profile_path': '/eBoC3425jmwRlsT2W8qUDsNwVXB.jpg',
  'cast_id': 55,
  'character': 'Theresa Hagen',
  'credit_id': '55c0e5ccc3a36823c9001c7c',
  'order': 24},
 {'adult': False,
  'gender': 2,
  'id': 3095,
  'known_for_department': 'Acting',
  'name': 'Gianni Russo',
  'original_name': 'Gianni Russo',
  'popularity': 6.963,
  'profile_path': '/5fjg2WPvuk1NvUpLyQ7aMJqOqy.jpg',
  'cast_id': 56,
  'character': 'Carlo Rizzi',
  'credit_id': '55c0e5ffc3a3682253001d4f',
  'order': 25},
 {'adult': False,
  'gender': 1,
  'id': 24697,
  'known_for_department': 'Acting',
  'name': 'Maria Carta',
  'original_name': 'Maria Carta',
  'popularity': 1.617,
  'profile_path': None,
  'cast_id': 57,
  'character': 'Mrs. Andolini',
  'credit_id': '55c0e6259251410f2a001d22',
  'order': 26},
 {'adult': False,
  'gender': 2,
  'id': 3280,
  'known_for_department': 'Acting',
  'name': 'Oreste Baldini',
  'original_name': 'Oreste Baldini',
  'popularity': 1.574,
  'profile_path': '/phS2muft9q6ta4DI7oay1WfSjh5.jpg',
  'cast_id': 33,
  'character': 'Young Vito',
  'credit_id': '52fe422bc3a36847f8009585',
  'order': 27},
 {'adult': False,
  'gender': 2,
  'id': 3333,
  'known_for_department': 'Acting',
  'name': 'Giuseppe Sillato',
  'original_name': 'Giuseppe Sillato',
  'popularity': 0.789,
  'profile_path': None,
  'cast_id': 35,
  'character': 'Don Francesco Ciccio',
  'credit_id': '52fe422bc3a36847f800958d',
  'order': 28},
 {'adult': False,
  'gender': 2,
  'id': 1343811,
  'known_for_department': 'Production',
  'name': 'Mario Cotone',
  'original_name': 'Mario Cotone',
  'popularity': 3.915,
  'profile_path': None,
  'cast_id': 58,
  'character': 'Don Tommasino',
  'credit_id': '55c0e6f5c3a36823c9001ca1',
  'order': 29},
 {'adult': False,
  'gender': 2,
  'id': 1503033,
  'known_for_department': 'Acting',
  'name': 'James Gounaris',
  'original_name': 'James Gounaris',
  'popularity': 1.925,
  'profile_path': None,
  'cast_id': 68,
  'character': 'Anthony Corleone',
  'credit_id': '55e52f7ec3a36813f80011d4',
  'order': 30},
 {'adult': False,
  'gender': 1,
  'id': 116739,
  'known_for_department': 'Acting',
  'name': 'Fay Spain',
  'original_name': 'Fay Spain',
  'popularity': 3.73,
  'profile_path': '/2N7wQIdFd329AZZDDt8mZp4ouUh.jpg',
  'cast_id': 43,
  'character': 'Mrs. Marcia Roth',
  'credit_id': '52fe422bc3a36847f80095af',
  'order': 31},
 {'adult': False,
  'gender': 2,
  'id': 5048,
  'known_for_department': 'Acting',
  'name': 'Harry Dean Stanton',
  'original_name': 'Harry Dean Stanton',
  'popularity': 7.336,
  'profile_path': '/197UiLVdxPOv8196sqmUpJzOQB5.jpg',
  'cast_id': 44,
  'character': 'F.B.I. Man #1',
  'credit_id': '52fe422bc3a36847f80095b3',
  'order': 32},
 {'adult': False,
  'gender': 2,
  'id': 3353549,
  'known_for_department': 'Acting',
  'name': 'David Baker',
  'original_name': 'David Baker',
  'popularity': 2.593,
  'profile_path': '/mQweTKYqvIjJWWeTuLDdVLMxOi5.jpg',
  'cast_id': 151,
  'character': 'F.B.I. Man #2',
  'credit_id': '61c0b1aa014325001f990a3a',
  'order': 33},
 {'adult': False,
  'gender': 2,
  'id': 133853,
  'known_for_department': 'Acting',
  'name': 'Carmine Caridi',
  'original_name': 'Carmine Caridi',
  'popularity': 5.01,
  'profile_path': '/5lmuAhZ1Trk8vDeRf64UZ1rHvV8.jpg',
  'cast_id': 59,
  'character': 'Carmine Rosato',
  'credit_id': '55c0e7c79251410f58001e67',
  'order': 34},
 {'adult': False,
  'gender': 2,
  'id': 1004,
  'known_for_department': 'Acting',
  'name': 'Danny Aiello',
  'original_name': 'Danny Aiello',
  'popularity': 9.238,
  'profile_path': '/e7Q6hgWilShqGZ572ByWF9eshMm.jpg',
  'cast_id': 45,
  'character': 'Tony Rosato',
  'credit_id': '52fe422bc3a36847f80095b7',
  'order': 35},
 {'adult': False,
  'gender': 2,
  'id': 14553,
  'known_for_department': 'Acting',
  'name': 'Carmine Foresta',
  'original_name': 'Carmine Foresta',
  'popularity': 1.709,
  'profile_path': None,
  'cast_id': 60,
  'character': 'Policeman',
  'credit_id': '55c0e80ac3a36823f7002165',
  'order': 36},
 {'adult': False,
  'gender': 2,
  'id': 1503034,
  'known_for_department': 'Acting',
  'name': 'Nick Discenza',
  'original_name': 'Nick Discenza',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 69,
  'character': 'Bartender',
  'credit_id': '55e52f7e92514137a000124d',
  'order': 37},
 {'adult': False,
  'gender': 2,
  'id': 1503035,
  'known_for_department': 'Acting',
  'name': 'Joseph Medaglia',
  'original_name': 'Joseph Medaglia',
  'popularity': 0.821,
  'profile_path': None,
  'cast_id': 70,
  'character': 'Father Carmelo',
  'credit_id': '55e52f7f925141379a001246',
  'order': 38},
 {'adult': False,
  'gender': 2,
  'id': 69948,
  'known_for_department': 'Writing',
  'name': 'William Bowers',
  'original_name': 'William Bowers',
  'popularity': 1.22,
  'profile_path': '/vpcZRLHdB6zJuKkvGhNTfvMKIdp.jpg',
  'cast_id': 156,
  'character': 'Senate Committee Chairman',
  'credit_id': '6489d651e272600147bc305d',
  'order': 39},
 {'adult': False,
  'gender': 2,
  'id': 1581646,
  'known_for_department': 'Acting',
  'name': 'Joseph Della Sorte',
  'original_name': 'Joseph Della Sorte',
  'popularity': 1.987,
  'profile_path': None,
  'cast_id': 111,
  'character': "Michael's Buttonman #1",
  'credit_id': '56cb9af5c3a36865ef0003ae',
  'order': 40},
 {'adult': False,
  'gender': 2,
  'id': 28413,
  'known_for_department': 'Acting',
  'name': 'Carmen Argenziano',
  'original_name': 'Carmen Argenziano',
  'popularity': 3.75,
  'profile_path': '/aiHWJmsVn7iWuohSg6lzF23XYVr.jpg',
  'cast_id': 112,
  'character': "Michael's Buttonman #2",
  'credit_id': '56cb9b0b9251412452000385',
  'order': 41},
 {'adult': False,
  'gender': 2,
  'id': 1503036,
  'known_for_department': 'Acting',
  'name': 'Joe Lo Grippo',
  'original_name': 'Joe Lo Grippo',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 71,
  'character': "Michael's Buttonman #3",
  'credit_id': '55e52f7fc3a3681408001327',
  'order': 42},
 {'adult': False,
  'gender': 2,
  'id': 1503037,
  'known_for_department': 'Acting',
  'name': 'Ezio Flagello',
  'original_name': 'Ezio Flagello',
  'popularity': 0.98,
  'profile_path': None,
  'cast_id': 72,
  'character': 'Impressario',
  'credit_id': '55e52f7f925141379d001174',
  'order': 43},
 {'adult': False,
  'gender': 2,
  'id': 1503038,
  'known_for_department': 'Acting',
  'name': 'Livio Giorgi',
  'original_name': 'Livio Giorgi',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 73,
  'character': "Tenor in 'Senza Mamma'",
  'credit_id': '55e52f80c3a36813f6000f76',
  'order': 44},
 {'adult': False,
  'gender': 1,
  'id': 76064,
  'known_for_department': 'Acting',
  'name': 'Kathleen Beller',
  'original_name': 'Kathleen Beller',
  'popularity': 6.311,
  'profile_path': '/gItmNmetGSbbRs656VgVFTRIFaQ.jpg',
  'cast_id': 62,
  'character': "Girl in 'Senza Mamma'",
  'credit_id': '55c0e921c3a36823f700217a',
  'order': 45},
 {'adult': False,
  'gender': 1,
  'id': 1503039,
  'known_for_department': 'Acting',
  'name': 'Saveria Mazzola',
  'original_name': 'Saveria Mazzola',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 74,
  'character': 'Signora Colombo',
  'credit_id': '55e52f8092514137a20010b9',
  'order': 46},
 {'adult': False,
  'gender': 2,
  'id': 1503040,
  'known_for_department': 'Acting',
  'name': 'Tito Alba',
  'original_name': 'Tito Alba',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 75,
  'character': 'Cuban President',
  'credit_id': '55e52f8092514137a600118b',
  'order': 47},
 {'adult': False,
  'gender': 2,
  'id': 1503041,
  'known_for_department': 'Acting',
  'name': 'Johnny Naranjo',
  'original_name': 'Johnny Naranjo',
  'popularity': 0.631,
  'profile_path': None,
  'cast_id': 76,
  'character': 'Cuban Translator',
  'credit_id': '55e52f8192514137a20010be',
  'order': 48},
 {'adult': False,
  'gender': 1,
  'id': 1503042,
  'known_for_department': 'Acting',
  'name': 'Elda Maida',
  'original_name': 'Elda Maida',
  'popularity': 0.692,
  'profile_path': None,
  'cast_id': 77,
  'character': "Pentangeli's Wife",
  'credit_id': '55e52f81c3a36813eb0011b4',
  'order': 49},
 {'adult': False,
  'gender': 2,
  'id': 1503043,
  'known_for_department': 'Acting',
  'name': 'Salvatore Po',
  'original_name': 'Salvatore Po',
  'popularity': 1.176,
  'profile_path': None,
  'cast_id': 78,
  'character': "Pentangeli's Brother",
  'credit_id': '55e52f81925141379d001179',
  'order': 50},
 {'adult': False,
  'gender': 2,
  'id': 1503044,
  'known_for_department': 'Acting',
  'name': 'Ignazio Pappalardo',
  'original_name': 'Ignazio Pappalardo',
  'popularity': 1.792,
  'profile_path': None,
  'cast_id': 79,
  'character': 'Mosca',
  'credit_id': '55e52f82c3a368140800132c',
  'order': 51},
 {'adult': False,
  'gender': 0,
  'id': 1503045,
  'known_for_department': 'Acting',
  'name': 'Andrea Maugeri',
  'original_name': 'Andrea Maugeri',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 80,
  'character': 'Strollo',
  'credit_id': '55e52f8292514137a0001252',
  'order': 52},
 {'adult': False,
  'gender': 0,
  'id': 1503046,
  'known_for_department': 'Acting',
  'name': 'Peter LaCorte',
  'original_name': 'Peter LaCorte',
  'popularity': 0.694,
  'profile_path': None,
  'cast_id': 81,
  'character': 'Signor Abbandando',
  'credit_id': '55e52f82925141379a00124c',
  'order': 53},
 {'adult': False,
  'gender': 0,
  'id': 1503047,
  'known_for_department': 'Acting',
  'name': 'Vincent Coppola',
  'original_name': 'Vincent Coppola',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 82,
  'character': 'Street Vendor',
  'credit_id': '55e52f82c3a3681402001036',
  'order': 54},
 {'adult': False,
  'gender': 2,
  'id': 14849,
  'known_for_department': 'Acting',
  'name': 'Peter Donat',
  'original_name': 'Peter Donat',
  'popularity': 2.999,
  'profile_path': '/9oxRUlGgSZCx58I8GKRKDbOIKyC.jpg',
  'cast_id': 83,
  'character': 'Questadt',
  'credit_id': '55e52f83925141379d00117e',
  'order': 55},
 {'adult': False,
  'gender': 2,
  'id': 1212995,
  'known_for_department': 'Acting',
  'name': 'Tom Dahlgren',
  'original_name': 'Tom Dahlgren',
  'popularity': 0.732,
  'profile_path': None,
  'cast_id': 84,
  'character': 'Fred Corngold',
  'credit_id': '55e52f8392514137a0001257',
  'order': 56},
 {'adult': False,
  'gender': 0,
  'id': 3353640,
  'known_for_department': 'Acting',
  'name': 'Paul B. Brown',
  'original_name': 'Paul B. Brown',
  'popularity': 0.6,
  'profile_path': None,
  'cast_id': 152,
  'character': 'Senator Ream',
  'credit_id': '61c0b285223e20009017b6f2',
  'order': 57},
 {'adult': False,
  'gender': 2,
  'id': 7768,
  'known_for_department': 'Production',
  'name': 'Phil Feldman',
  'original_name': 'Phil Feldman',
  'popularity': 1.566,
  'profile_path': None,
  'cast_id': 85,
  'character': 'Senator #1',
  'credit_id': '55e52f8392514137a80011ad',
  'order': 58},
 {'adult': False,
  'gender': 2,
  'id': 102429,
  'known_for_department': 'Production',
  'name': 'Roger Corman',
  'original_name': 'Roger Corman',
  'popularity': 6.094,
  'profile_path': '/kWvtdBp4AVSOwluWwZ1WhsKlAfk.jpg',
  'cast_id': 46,
  'character': 'Senator #2',
  'credit_id': '52fe422bc3a36847f80095bb',
  'order': 59},
 {'adult': False,
  'gender': 1,
  'id': 46929,
  'known_for_department': 'Acting',
  'name': 'Ivonne Coll',
  'original_name': 'Ivonne Coll',
  'popularity': 3.057,
  'profile_path': '/7cyzeWeX8zD4IwAUDfyE9BK8woY.jpg',
  'cast_id': 63,
  'character': 'Yolanda',
  'credit_id': '55c0e94bc3a36823c9001cca',
  'order': 60},
 {'adult': False,
  'gender': 0,
  'id': 1205819,
  'known_for_department': 'Acting',
  'name': 'Joe De Nicola',
  'original_name': 'Joe De Nicola',
  'popularity': 0.98,
  'profile_path': None,
  'cast_id': 86,
  'character': 'Attendant at Brothel',
  'credit_id': '55e52f84c3a36813eb0011b9',
  'order': 61},
 {'adult': False,
  'gender': 0,

In [11]:
movies_crew=pd.DataFrame()

In [12]:
for i in movies_id:
    headers = {"accept": "application/json","Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNzJhZmMwNjQ2NzU5N2FkY2QwMTE0YjFkYWQwZDBiMCIsInN1YiI6IjYyZGQ0NmQxZWE4NGM3MDA2NzRhYTU1ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.10QUa8JMYbIZ1ljSPJF-sXfe389uc5Hpck-J8laFen4"}
    response = requests.get("https://api.themoviedb.org/3/movie/{}/credits?language=en-US".format(i) ,headers=headers)
    data = [[i,response.json().get('crew')]]
    temp = pd.DataFrame(data,columns=['id','crew'])
    movies_crew = movies_crew.append(temp,ignore_index=True)

In [13]:
movies_crew

          id                                               crew
0        238  [{'adult': False, 'gender': 2, 'id': 154, 'kno...
1        278  [{'adult': False, 'gender': 2, 'id': 153, 'kno...
2        240  [{'adult': False, 'gender': 2, 'id': 154, 'kno...
3        424  [{'adult': False, 'gender': 2, 'id': 491, 'kno...
4      19404  [{'adult': False, 'gender': 1, 'id': 8311, 'kn...
...      ...                                                ...
9995  124459  [{'adult': False, 'gender': 2, 'id': 298, 'kno...
9996  523931  [{'adult': False, 'gender': 2, 'id': 30053, 'k...
9997  265208  [{'adult': False, 'gender': 0, 'id': 297, 'kno...
9998   51170  [{'adult': False, 'gender': 2, 'id': 12095, 'k...
9999   39451  [{'adult': False, 'gender': 2, 'id': 380, 'kno...

[10000 rows x 2 columns]

In [14]:
movies_crew['crew'][2]

[{'adult': False,
  'gender': 2,
  'id': 154,
  'known_for_department': 'Editing',
  'name': 'Walter Murch',
  'original_name': 'Walter Murch',
  'popularity': 2.679,
  'profile_path': '/kQh7U7kRLF9NKEMpxiGjZEIu0o3.jpg',
  'credit_id': '6489dd6be375c00139c283ed',
  'department': 'Sound',
  'job': 'Sound Editor'},
 {'adult': False,
  'gender': 2,
  'id': 154,
  'known_for_department': 'Editing',
  'name': 'Walter Murch',
  'original_name': 'Walter Murch',
  'popularity': 2.679,
  'profile_path': '/kQh7U7kRLF9NKEMpxiGjZEIu0o3.jpg',
  'credit_id': '5a773d1f9251417763000e61',
  'department': 'Sound',
  'job': 'Sound Re-Recording Mixer'},
 {'adult': False,
  'gender': 2,
  'id': 1776,
  'known_for_department': 'Directing',
  'name': 'Francis Ford Coppola',
  'original_name': 'Francis Ford Coppola',
  'popularity': 4.136,
  'profile_path': '/3Pblihd6KjXliie9vj4iQJwbNPU.jpg',
  'credit_id': '5e9251c384448e00128f09b1',
  'department': 'Writing',
  'job': 'Screenplay'},
 {'adult': False,
  'gender': 2,
  'id': 1776,
  'known_for_department': 'Directing',
  'name': 'Francis Ford Coppola',
  'original_name': 'Francis Ford Coppola',
  'popularity': 4.136,
  'profile_path': '/3Pblihd6KjXliie9vj4iQJwbNPU.jpg',
  'credit_id': '5e92517a8e87020016cb1d0e',
  'department': 'Directing',
  'job': 'Director'},
 {'adult': False,
  'gender': 2,
  'id': 1776,
  'known_for_department': 'Directing',
  'name': 'Francis Ford Coppola',
  'original_name': 'Francis Ford Coppola',
  'popularity': 4.136,
  'profile_path': '/3Pblihd6KjXliie9vj4iQJwbNPU.jpg',
  'credit_id': '52fe422bc3a36847f80094e3',
  'department': 'Production',
  'job': 'Producer'},
 {'adult': False,
  'gender': 2,
  'id': 2870,
  'known_for_department': 'Production',
  'name': 'Gray Frederickson',
  'original_name': 'Gray Frederickson',
  'popularity': 0.652,
  'profile_path': None,
  'credit_id': '6489dce86f8d9500e5016b8b',
  'department': 'Production',
  'job': 'Co-Producer'},
 {'adult': False,
  'gender': 2,
  'id': 2871,
  'known_for_department': 'Production',
  'name': 'Fred Roos',
  'original_name': 'Fred Roos',
  'popularity': 4.123,
  'profile_path': '/qfXLY5E589l0TQnoayWmUrBDsgo.jpg',
  'credit_id': '6489dcdae272600147bc32bf',
  'department': 'Production',
  'job': 'Co-Producer'},
 {'adult': False,
  'gender': 0,
  'id': 3170,
  'known_for_department': 'Production',
  'name': 'Mona Skager',
  'original_name': 'Mona Skager',
  'popularity': 0.84,
  'profile_path': None,
  'credit_id': '6489dcf8293835011ea4d126',
  'department': 'Production',
  'job': 'Associate Producer'},
 {'adult': False,
  'gender': 2,
  'id': 2872,
  'known_for_department': 'Sound',
  'name': 'Carmine Coppola',
  'original_name': 'Carmine Coppola',
  'popularity': 4.22,
  'profile_path': '/iURpKXIgdtQoVCBQ8GKGvb0Qw5z.jpg',
  'credit_id': '6489d964bf31f250569de661',
  'department': 'Crew',
  'job': 'Additional Music'},
 {'adult': False,
  'gender': 2,
  'id': 2872,
  'known_for_department': 'Sound',
  'name': 'Carmine Coppola',
  'original_name': 'Carmine Coppola',
  'popularity': 4.22,
  'profile_path': '/iURpKXIgdtQoVCBQ8GKGvb0Qw5z.jpg',
  'credit_id': '6489d971e2726001287c1de0',
  'department': 'Sound',
  'job': 'Conductor'},
 {'adult': False,
  'gender': 2,
  'id': 3176,
  'known_for_department': 'Production',
  'name': 'Vic Ramos',
  'original_name': 'Vic Ramos',
  'popularity': 0.972,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f8009565',
  'department': 'Production',
  'job': 'Casting'},
 {'adult': False,
  'gender': 2,
  'id': 2875,
  'known_for_department': 'Art',
  'name': 'Dean Tavoularis',
  'original_name': 'Dean Tavoularis',
  'popularity': 3.412,
  'profile_path': '/hrRBaXUn2k29qd1MvAxuag5L32c.jpg',
  'credit_id': '52fe422bc3a36847f8009541',
  'department': 'Art',
  'job': 'Production Design'},
 {'adult': False,
  'gender': 2,
  'id': 794,
  'known_for_department': 'Art',
  'name': 'Angelo P. Graham',
  'original_name': 'Angelo P. Graham',
  'popularity': 1.039,
  'profile_path': None,
  'credit_id': '57471cb39251415f60002932',
  'department': 'Art',
  'job': 'Art Direction'},
 {'adult': False,
  'gender': 2,
  'id': 8339,
  'known_for_department': 'Art',
  'name': 'George R. Nelson',
  'original_name': 'George R. Nelson',
  'popularity': 1.628,
  'profile_path': None,
  'credit_id': '57471d159251415e5d002c69',
  'department': 'Art',
  'job': 'Set Decoration'},
 {'adult': False,
  'gender': 1,
  'id': 597,
  'known_for_department': 'Production',
  'name': 'Jane Feinberg',
  'original_name': 'Jane Feinberg',
  'popularity': 3.539,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f8009559',
  'department': 'Production',
  'job': 'Casting'},
 {'adult': False,
  'gender': 2,
  'id': 598,
  'known_for_department': 'Production',
  'name': 'Mike Fenton',
  'original_name': 'Mike Fenton',
  'popularity': 3.777,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f800955f',
  'department': 'Production',
  'job': 'Casting'},
 {'adult': False,
  'gender': 0,
  'id': 1054,
  'known_for_department': 'Sound',
  'name': 'James Fritch',
  'original_name': 'James Fritch',
  'popularity': 1.094,
  'profile_path': None,
  'credit_id': '6489ddb9e375c000ff4acb3d',
  'department': 'Sound',
  'job': 'Sound Effects Editor'},
 {'adult': False,
  'gender': 2,
  'id': 2988,
  'known_for_department': 'Editing',
  'name': 'Barry Malkin',
  'original_name': 'Barry Malkin',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f8009547',
  'department': 'Editing',
  'job': 'Editor'},
 {'adult': False,
  'gender': 2,
  'id': 3083,
  'known_for_department': 'Writing',
  'name': 'Mario Puzo',
  'original_name': 'Mario Puzo',
  'popularity': 3.543,
  'profile_path': '/lEsT1uCZAZg1nYDQe3Fsj9CalzT.jpg',
  'credit_id': '64c8795a1fa1c800b0c15bbe',
  'department': 'Writing',
  'job': 'Screenplay'},
 {'adult': False,
  'gender': 2,
  'id': 3083,
  'known_for_department': 'Writing',
  'name': 'Mario Puzo',
  'original_name': 'Mario Puzo',
  'popularity': 3.543,
  'profile_path': '/lEsT1uCZAZg1nYDQe3Fsj9CalzT.jpg',
  'credit_id': '52fe422bc3a36847f80094fb',
  'department': 'Writing',
  'job': 'Novel'},
 {'adult': False,
  'gender': 2,
  'id': 3085,
  'known_for_department': 'Acting',
  'name': 'James Caan',
  'original_name': 'James Caan',
  'popularity': 15.596,
  'profile_path': '/v3flJtQEyczxENi29yJyvnN6LVt.jpg',
  'credit_id': '57472235c3a36839df000077',
  'department': 'Crew',
  'job': 'Thanks'},
 {'adult': False,
  'gender': 2,
  'id': 3097,
  'known_for_department': 'Camera',
  'name': 'Gordon Willis',
  'original_name': 'Gordon Willis',
  'popularity': 1.22,
  'profile_path': '/6gOmfatlF7UdhaHi2tPsZMb5vmz.jpg',
  'credit_id': '52fe422bc3a36847f800952f',
  'department': 'Camera',
  'job': 'Director of Photography'},
 {'adult': False,
  'gender': 2,
  'id': 3098,
  'known_for_department': 'Sound',
  'name': 'Nino Rota',
  'original_name': 'Nino Rota',
  'popularity': 0.833,
  'profile_path': '/v42v3uM7jqwoZxDJ8MlEtT6Ol7a.jpg',
  'credit_id': '52fe422bc3a36847f800953b',
  'department': 'Sound',
  'job': 'Original Music Composer'},
 {'adult': False,
  'gender': 2,
  'id': 3100,
  'known_for_department': 'Editing',
  'name': 'Peter Zinner',
  'original_name': 'Peter Zinner',
  'popularity': 2.856,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f8009553',
  'department': 'Editing',
  'job': 'Editor'},
 {'adult': False,
  'gender': 2,
  'id': 3102,
  'known_for_department': 'Sound',
  'name': 'Howard Beals',
  'original_name': 'Howard Beals',
  'popularity': 0.972,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f800956b',
  'department': 'Sound',
  'job': 'Sound Effects Editor'},
 {'adult': False,
  'gender': 2,
  'id': 3175,
  'known_for_department': 'Editing',
  'name': 'Richard Marks',
  'original_name': 'Richard Marks',
  'popularity': 1.382,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f800954d',
  'department': 'Editing',
  'job': 'Editor'},
 {'adult': False,
  'gender': 2,
  'id': 3177,
  'known_for_department': 'Sound',
  'name': 'Mark Berger',
  'original_name': 'Mark Berger',
  'popularity': 0.98,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f8009571',
  'department': 'Sound',
  'job': 'Sound Montage Associate'},
 {'adult': False,
  'gender': 2,
  'id': 3178,
  'known_for_department': 'Sound',
  'name': 'Nathan Boxer',
  'original_name': 'Nathan Boxer',
  'popularity': 0.619,
  'profile_path': None,
  'credit_id': '6489dd9b29383500e4c5d22f',
  'department': 'Sound',
  'job': 'Sound Recordist'},
 {'adult': False,
  'gender': 0,
  'id': 3179,
  'known_for_department': 'Sound',
  'name': 'George Brand',
  'original_name': 'George Brand',
  'popularity': 0.7,
  'profile_path': None,
  'credit_id': '52fe422bc3a36847f800957d',
  'department': 'Sound',
  'job': 'Music Editor'},
 {'adult': False,
  'gender': 2,
  'id': 18373,
  'known_for_department': 'Camera',
  'name': 'Ralph Gerling',
  'original_name': 'Ralph Gerling',
  'popularity': 1.566,
  'profile_path': None,
  'credit_id': '56cf3dda9251413e62003001',
  'department': 'Camera',
  'job': 'Camera Operator'},
 {'adult': False,
  'gender': 2,
  'id': 6099,
  'known_for_department': 'Production',
  'name': 'Valerio De Paolis',
  'original_name': 'Valerio De Paolis',
  'popularity': 0.6,
  'profile_path': '/rbsYkbJPgQAMuFY71RYrYatdXWT.jpg',
  'credit_id': '563e3d519251416cd8003e2d',
  'department': 'Production',
  'job': 'Production Supervisor'},
 {'adult': False,
  'gender': 1,
  'id': 6455,
  'known_for_department': 'Costume & Make-Up',
  'name': 'Theadora Van Runkle',
  'original_name': 'Theadora Van Runkle',
  'popularity': 0.648,
  'profile_path': None,
  'credit_id': '5a773cdec3a368224e000e64',
  'department': 'Costume & Make-Up',
  'job': 'Costume Design'},
 {'adult': False,
  'gender': 2,
  'id': 16654,
  'known_for_department': 'Production',
  'name': 'Michael S. Glick',
  'original_name': 'Michael S. Glick',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '57471dc39251417694000543',
  'department': 'Production',
  'job': 'Production Manager'},
 {'adult': False,
  'gender': 2,
  'id': 29654,
  'known_for_department': 'Costume & Make-Up',
  'name': 'Dick Smith',
  'original_name': 'Dick Smith',
  'popularity': 0.84,
  'profile_path': '/kKCenlQ8iQCTLGfX8ZPpJFpxvwS.jpg',
  'credit_id': '56a77044c3a36819da0030a1',
  'department': 'Costume & Make-Up',
  'job': 'Makeup Artist'},
 {'adult': False,
  'gender': 2,
  'id': 81538,
  'known_for_department': 'Art',
  'name': 'Wayne Fitzgerald',
  'original_name': 'Wayne Fitzgerald',
  'popularity': 0.811,
  'profile_path': None,
  'credit_id': '644515f8b3f6f502fc9f189a',
  'department': 'Art',
  'job': 'Title Designer'},
 {'adult': False,
  'gender': 2,
  'id': 70250,
  'known_for_department': 'Directing',
  'name': 'Newt Arnold',
  'original_name': 'Newt Arnold',
  'popularity': 3.975,
  'profile_path': None,
  'credit_id': '56cf3a4bc3a3681e57002da7',
  'department': 'Directing',
  'job': 'Assistant Director'},
 {'adult': False,
  'gender': 2,
  'id': 96912,
  'known_for_department': 'Crew',
  'name': 'Joe Lombardi',
  'original_name': 'Joe Lombardi',
  'popularity': 1.707,
  'profile_path': None,
  'credit_id': '574485d8c3a36807640008d1',
  'department': 'Crew',
  'job': 'Special Effects'},
 {'adult': False,
  'gender': 0,
  'id': 102589,
  'known_for_department': 'Directing',
  'name': 'Michael Kusley',
  'original_name': 'Michael Kusley',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '6489dabae375c000e251c431',
  'department': 'Directing',
  'job': 'Second Assistant Director'},
 {'adult': False,
  'gender': 0,
  'id': 557873,
  'known_for_department': 'Camera',
  'name': 'Bob Rose',
  'original_name': 'Bob Rose',
  'popularity': 0.652,
  'profile_path': None,
  'credit_id': '6489dc0ebf31f25054b83e7e',
  'department': 'Camera',
  'job': 'Key Grip'},
 {'adult': False,
  'gender': 2,
  'id': 1343811,
  'known_for_department': 'Production',
  'name': 'Mario Cotone',
  'original_name': 'Mario Cotone',
  'popularity': 3.915,
  'profile_path': None,
  'credit_id': '57471d8c92514177b00013f1',
  'department': 'Production',
  'job': 'Unit Manager'},
 {'adult': False,
  'gender': 0,
  'id': 1359894,
  'known_for_department': 'Production',
  'name': 'Burt Bluestein',
  'original_name': 'Burt Bluestein',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '6489da9fe375c00139c282cd',
  'department': 'Directing',
  'job': 'Second Assistant Director'},
 {'adult': False,
  'gender': 2,
  'id': 1409008,
  'known_for_department': 'Costume & Make-Up',
  'name': 'Charles H. Schram',
  'original_name': 'Charles H. Schram',
  'popularity': 1.725,
  'profile_path': '/fdY09ub1rX0yYh8qcPrWtQurpfi.jpg',
  'credit_id': '56985c419251412546001488',
  'department': 'Costume & Make-Up',
  'job': 'Makeup Artist'},
 {'adult': False,
  'gender': 0,
  'id': 1419935,
  'known_for_department': 'Costume & Make-Up',
  'name': 'Naomi Cavin',
  'original_name': 'Naomi Cavin',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '56a7705a92514129f5002fed',
  'department': 'Costume & Make-Up',
  'job': 'Hairstylist'},
 {'adult': False,
  'gender': 0,
  'id': 1427699,
  'known_for_department': 'Directing',
  'name': 'John Franco',
  'original_name': 'John Franco',
  'popularity': 1.033,
  'profile_path': None,
  'credit_id': '566b7a09c3a3682e98005c33',
  'department': 'Directing',
  'job': 'Script Supervisor'},
 {'adult': False,
  'gender': 1,
  'id': 1469560,
  'known_for_department': 'Crew',
  'name': 'Eileen Peterson',
  'original_name': 'Eileen Peterson',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '574dc0d7c3a36858bd0000a0',
  'department': 'Crew',
  'job': 'Unit Publicist'},
 {'adult': False,
  'gender': 0,
  'id': 1511706,
  'known_for_department': 'Sound',
  'name': 'Charles M. Wilborn',
  'original_name': 'Charles M. Wilborn',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '58e3cd81925141281902066f',
  'department': 'Sound',
  'job': 'Sound Recordist'},
 {'adult': False,
  'gender': 0,
  'id': 1511713,
  'known_for_department': 'Production',
  'name': 'Jack English',
  'original_name': 'Jack English',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '5e7be9864350113e61257d0f',
  'department': 'Production',
  'job': 'Location Coordinator'},
 {'adult': False,
  'gender': 0,
  'id': 1518593,
  'known_for_department': 'Directing',
  'name': 'B.J. Bjorkman',
  'original_name': 'B.J. Bjorkman',
  'popularity': 0.98,
  'profile_path': None,
  'credit_id': '5751b60cc3a3683040000219',
  'department': 'Directing',
  'job': 'Script Supervisor'},
 {'adult': False,
  'gender': 0,
  'id': 1535121,
  'known_for_department': 'Lighting',
  'name': 'George Holmes',
  'original_name': 'George Holmes',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '5c6dd75992514120d504f307',
  'department': 'Lighting',
  'job': 'Gaffer'},
 {'adult': False,
  'gender': 2,
  'id': 1625347,
  'known_for_department': 'Directing',
  'name': 'Tony Brandt',
  'original_name': 'Tony Brandt',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '57447c8192514110fb00068e',
  'department': 'Directing',
  'job': 'Assistant Director'},
 {'adult': False,
  'gender': 0,
  'id': 1630221,
  'known_for_department': 'Directing',
  'name': 'Alan Hopkins',
  'original_name': 'Alan Hopkins',
  'popularity': 0.996,
  'profile_path': None,
  'credit_id': '6489daeb6f8d95013c754489',
  'department': 'Directing',
  'job': 'Second Assistant Director'},
 {'adult': False,
  'gender': 0,
  'id': 1783080,
  'known_for_department': 'Production',
  'name': 'Henry J. Lange Jr.',
  'original_name': 'Henry J. Lange Jr.',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '6489db0c99259c00e2f77703',
  'department': 'Directing',
  'job': 'Second Assistant Director'},
 {'adult': False,
  'gender': 2,
  'id': 1966431,
  'known_for_department': 'Directing',
  'name': 'Charles Myers',
  'original_name': 'Charles Myers',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '6489db21293835013c342add',
  'department': 'Directing',
  'job': 'Second Assistant Director'},
 {'adult': False,
  'gender': 1,
  'id': 2930663,
  'known_for_department': 'Acting',
  'name': 'Mona Houghton',
  'original_name': 'Mona Houghton',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '5ffb1499a3b5e60040367dc2',
  'department': 'Production',
  'job': 'Location Assistant'},
 {'adult': False,
  'gender': 2,
  'id': 4111358,
  'known_for_department': 'Crew',
  'name': 'A.D. Flowers',
  'original_name': 'A.D. Flowers',
  'popularity': 0.6,
  'profile_path': None,
  'credit_id': '6489dc65d2b20900ebc27798',
  'department': 'Crew',
  'job': 'Special Effects'}]

In [15]:
movies_genres = pd.DataFrame()

In [16]:
for i in movies_id:
    headers = {"accept": "application/json","Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNzJhZmMwNjQ2NzU5N2FkY2QwMTE0YjFkYWQwZDBiMCIsInN1YiI6IjYyZGQ0NmQxZWE4NGM3MDA2NzRhYTU1ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.10QUa8JMYbIZ1ljSPJF-sXfe389uc5Hpck-J8laFen4"}
    response = requests.get("https://api.themoviedb.org/3/movie/{}?language=en-US".format(i) ,headers=headers)
    data = [[i,response.json().get('genres')]]
    temp = pd.DataFrame(data,columns=['id','genres'])
    movies_genres = movies_genres.append(temp,ignore_index=True)

In [17]:
movies_genres

          id                                             genres
0        238  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
1        278  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
2        240  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
3        424  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...
4      19404  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
...      ...                                                ...
9995  124459                     [{'id': 35, 'name': 'Comedy'}]
9996  523931  [{'id': 28, 'name': 'Action'}, {'id': 878, 'na...
9997  265208  [{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...
9998   51170  [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...
9999   39451  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...

[10000 rows x 2 columns]

In [18]:
movies_genres['genres'][0]

[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]

In [19]:
movies_keywords = pd.DataFrame()

In [20]:
for i in movies_id:
    headers = {"accept": "application/json","Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNzJhZmMwNjQ2NzU5N2FkY2QwMTE0YjFkYWQwZDBiMCIsInN1YiI6IjYyZGQ0NmQxZWE4NGM3MDA2NzRhYTU1ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.10QUa8JMYbIZ1ljSPJF-sXfe389uc5Hpck-J8laFen4"} 
    response = requests.get("https://api.themoviedb.org/3/movie/{}/keywords".format(i) ,headers=headers)
    data = [[i,response.json().get('keywords')]]
    temp = pd.DataFrame(data,columns=['id','keywords'])
    movies_keywords = movies_keywords.append(temp,ignore_index=True)

In [21]:
movies_keywords

          id                                           keywords
0        238  [{'id': 131, 'name': 'italy'}, {'id': 697, 'na...
1        278  [{'id': 378, 'name': 'prison'}, {'id': 417, 'n...
2        240  [{'id': 131, 'name': 'italy'}, {'id': 700, 'na...
3        424  [{'id': 818, 'name': 'based on novel or book'}...
4      19404  [{'id': 2783, 'name': 'family's daily life'}, ...
...      ...                                                ...
9995  124459  [{'id': 2343, 'name': 'magic'}, {'id': 14570, ...
9996  523931  [{'id': 339, 'name': 'submarine'}, {'id': 1299...
9997  265208  [{'id': 395, 'name': 'gambling'}, {'id': 3088,...
9998   51170  [{'id': 291, 'name': 'circus'}, {'id': 6054, '...
9999   39451  [{'id': 428, 'name': 'nurse'}, {'id': 977, 'na...

[10000 rows x 2 columns]

In [22]:
movies_keywords['keywords'][2]

[{'id': 131, 'name': 'italy'},
 {'id': 700, 'name': 'italian american'},
 {'id': 701, 'name': 'cuba'},
 {'id': 1715, 'name': 'symbolism'},
 {'id': 3149, 'name': 'gangster'},
 {'id': 4232, 'name': 'melancholy'},
 {'id': 6049, 'name': 'praise'},
 {'id': 9748, 'name': 'revenge'},
 {'id': 10291, 'name': 'organized crime'},
 {'id': 10391, 'name': 'mafia'},
 {'id': 10909, 'name': 'lawyer'},
 {'id': 14632, 'name': 'suburb'},
 {'id': 156024, 'name': 'corrupt politician'}]

In [23]:
movies_new = movies_new.merge(movies_cast, on=['id'])
movies_new = movies_new.merge(movies_crew, on=['id'])
movies_new = movies_new.merge(movies_keywords, on=['id'])
movies_new = movies_new.merge(movies_genres,on=['id'])

movies_new

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[{'adult': False, 'gender': 2, 'id': 3084, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[{'id': 131, 'name': 'italy'}, {'id': 697, 'na...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[{'adult': False, 'gender': 2, 'id': 504, 'kno...","[{'adult': False, 'gender': 2, 'id': 153, 'kno...","[{'id': 378, 'name': 'prison'}, {'id': 417, 'n...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[{'adult': False, 'gender': 2, 'id': 1158, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[{'id': 131, 'name': 'italy'}, {'id': 700, 'na...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[{'adult': False, 'gender': 2, 'id': 3896, 'kn...","[{'adult': False, 'gender': 2, 'id': 491, 'kno...","[{'id': 818, 'name': 'based on novel or book'}...","[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name..."
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...","[{'id': 2783, 'name': 'family's daily life'}, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
...,...,...,...,...,...,...,...
9995,124459,The Incredible Burt Wonderstone,After breaking up with his longtime stage part...,"[{'adult': False, 'gender': 2, 'id': 4495, 'kn...","[{'adult': False, 'gender': 2, 'id': 298, 'kno...","[{'id': 2343, 'name': 'magic'}, {'id': 14570, ...","[{'id': 35, 'name': 'Comedy'}]"
9996,523931,Megalodon,A military vessel on the search for an unident...,"[{'adult': False, 'gender': 2, 'id': 147, 'kno...","[{'adult': False, 'gender': 2, 'id': 30053, 'k...","[{'id': 339, 'name': 'submarine'}, {'id': 1299...","[{'id': 28, 'name': 'Action'}, {'id': 878, 'na..."
9997,265208,Wild Card,When a Las Vegas bodyguard with lethal skills ...,"[{'adult': False, 'gender': 2, 'id': 976, 'kno...","[{'adult': False, 'gender': 0, 'id': 297, 'kno...","[{'id': 395, 'name': 'gambling'}, {'id': 3088,...","[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n..."
9998,51170,Open Season 3,"Boog, Elliot, and their forest friends return ...","[{'adult': False, 'gender': 2, 'id': 1239270, ...","[{'adult': False, 'gender': 2, 'id': 12095, 'k...","[{'id': 291, 'name': 'circus'}, {'id': 6054, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 16, '..."
9999,39451,Little Fockers,"It has taken 10 years, two little Fockers with...","[{'adult': False, 'gender': 2, 'id': 380, 'kno...","[{'adult': False, 'gender': 2, 'id': 380, 'kno...","[{'id': 428, 'name': 'nurse'}, {'id': 977, 'na...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '..."

In [24]:
movies_new.to_csv('Final_Dataset.csv', index=False, mode='a')

In [25]:
movies_new

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[{'adult': False, 'gender': 2, 'id': 3084, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[{'id': 131, 'name': 'italy'}, {'id': 697, 'na...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[{'adult': False, 'gender': 2, 'id': 504, 'kno...","[{'adult': False, 'gender': 2, 'id': 153, 'kno...","[{'id': 378, 'name': 'prison'}, {'id': 417, 'n...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[{'adult': False, 'gender': 2, 'id': 1158, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[{'id': 131, 'name': 'italy'}, {'id': 700, 'na...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[{'adult': False, 'gender': 2, 'id': 3896, 'kn...","[{'adult': False, 'gender': 2, 'id': 491, 'kno...","[{'id': 818, 'name': 'based on novel or book'}...","[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name..."
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...","[{'id': 2783, 'name': 'family's daily life'}, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
...,...,...,...,...,...,...,...
9995,124459,The Incredible Burt Wonderstone,After breaking up with his longtime stage part...,"[{'adult': False, 'gender': 2, 'id': 4495, 'kn...","[{'adult': False, 'gender': 2, 'id': 298, 'kno...","[{'id': 2343, 'name': 'magic'}, {'id': 14570, ...","[{'id': 35, 'name': 'Comedy'}]"
9996,523931,Megalodon,A military vessel on the search for an unident...,"[{'adult': False, 'gender': 2, 'id': 147, 'kno...","[{'adult': False, 'gender': 2, 'id': 30053, 'k...","[{'id': 339, 'name': 'submarine'}, {'id': 1299...","[{'id': 28, 'name': 'Action'}, {'id': 878, 'na..."
9997,265208,Wild Card,When a Las Vegas bodyguard with lethal skills ...,"[{'adult': False, 'gender': 2, 'id': 976, 'kno...","[{'adult': False, 'gender': 0, 'id': 297, 'kno...","[{'id': 395, 'name': 'gambling'}, {'id': 3088,...","[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n..."
9998,51170,Open Season 3,"Boog, Elliot, and their forest friends return ...","[{'adult': False, 'gender': 2, 'id': 1239270, ...","[{'adult': False, 'gender': 2, 'id': 12095, 'k...","[{'id': 291, 'name': 'circus'}, {'id': 6054, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 16, '..."
9999,39451,Little Fockers,"It has taken 10 years, two little Fockers with...","[{'adult': False, 'gender': 2, 'id': 380, 'kno...","[{'adult': False, 'gender': 2, 'id': 380, 'kno...","[{'id': 428, 'name': 'nurse'}, {'id': 977, 'na...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '..."