In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('Final_Dataset.csv')

In [3]:
movies

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[{'adult': False, 'gender': 2, 'id': 3084, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[{'id': 131, 'name': 'italy'}, {'id': 697, 'na...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[{'adult': False, 'gender': 2, 'id': 504, 'kno...","[{'adult': False, 'gender': 2, 'id': 153, 'kno...","[{'id': 378, 'name': 'prison'}, {'id': 417, 'n...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[{'adult': False, 'gender': 2, 'id': 1158, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[{'id': 131, 'name': 'italy'}, {'id': 700, 'na...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[{'adult': False, 'gender': 2, 'id': 3896, 'kn...","[{'adult': False, 'gender': 2, 'id': 491, 'kno...","[{'id': 818, 'name': 'based on novel or book'}...","[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name..."
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...","[{'id': 2783, 'name': ""family's daily life""}, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
...,...,...,...,...,...,...,...
9995,124459,The Incredible Burt Wonderstone,After breaking up with his longtime stage part...,"[{'adult': False, 'gender': 2, 'id': 4495, 'kn...","[{'adult': False, 'gender': 2, 'id': 298, 'kno...","[{'id': 2343, 'name': 'magic'}, {'id': 14570, ...","[{'id': 35, 'name': 'Comedy'}]"
9996,523931,Megalodon,A military vessel on the search for an unident...,"[{'adult': False, 'gender': 2, 'id': 147, 'kno...","[{'adult': False, 'gender': 2, 'id': 30053, 'k...","[{'id': 339, 'name': 'submarine'}, {'id': 1299...","[{'id': 28, 'name': 'Action'}, {'id': 878, 'na..."
9997,265208,Wild Card,When a Las Vegas bodyguard with lethal skills ...,"[{'adult': False, 'gender': 2, 'id': 976, 'kno...","[{'adult': False, 'gender': 0, 'id': 297, 'kno...","[{'id': 395, 'name': 'gambling'}, {'id': 3088,...","[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n..."
9998,51170,Open Season 3,"Boog, Elliot, and their forest friends return ...","[{'adult': False, 'gender': 2, 'id': 1239270, ...","[{'adult': False, 'gender': 2, 'id': 12095, 'k...","[{'id': 291, 'name': 'circus'}, {'id': 6054, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 16, '..."
9999,39451,Little Fockers,"It has taken 10 years, two little Fockers with...","[{'adult': False, 'gender': 2, 'id': 380, 'kno...","[{'adult': False, 'gender': 2, 'id': 380, 'kno...","[{'id': 428, 'name': 'nurse'}, {'id': 977, 'na...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '..."

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10000 non-null  int64
 1   title     10000 non-null  object
 2   overview  9998 non-null   object
 3   Actors    10000 non-null  object
 4   crew      10000 non-null  object
 5   keywords  10000 non-null  object
 6   genres    10000 non-null  object
dtypes: int64(1), object(6)
memory usage: 547.0+ KB

In [5]:
movies.isnull().sum()

id          0
title       0
overview    2
Actors      0
crew        0
keywords    0
genres      0
dtype: int64

In [6]:
movies.duplicated().sum()

0

In [7]:
movies.iloc[0].genres

"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]"

In [8]:
import ast

def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [9]:
movies['genres']= movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [10]:
movies.head()

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[{'adult': False, 'gender': 2, 'id': 3084, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[italy, loss of loved one, love at first sight...","[Drama, Crime]"
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[{'adult': False, 'gender': 2, 'id': 504, 'kno...","[{'adult': False, 'gender': 2, 'id': 153, 'kno...","[prison, corruption, police brutality, based o...","[Drama, Crime]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[{'adult': False, 'gender': 2, 'id': 1158, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[italy, italian american, cuba, symbolism, gan...","[Drama, Crime]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[{'adult': False, 'gender': 2, 'id': 3896, 'kn...","[{'adult': False, 'gender': 2, 'id': 491, 'kno...","[based on novel or book, factory, concentratio...","[Drama, History, War]"
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...","[family's daily life, family history, love-hat...","[Comedy, Drama, Romance]"

In [11]:
movies['Actors'][0]

'[{\'adult\': False, \'gender\': 2, \'id\': 3084, \'known_for_department\': \'Acting\', \'name\': \'Marlon Brando\', \'original_name\': \'Marlon Brando\', \'popularity\': 13.139, \'profile_path\': \'/5o8whyfLBWXLODEcMP8K45lPTjT.jpg\', \'cast_id\': 146, \'character\': \'Don Vito Corleone\', \'credit_id\': \'6489aa85e2726001072483a9\', \'order\': 0}, {\'adult\': False, \'gender\': 2, \'id\': 1158, \'known_for_department\': \'Acting\', \'name\': \'Al Pacino\', \'original_name\': \'Al Pacino\', \'popularity\': 31.831, \'profile_path\': \'/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg\', \'cast_id\': 147, \'character\': \'Michael Corleone\', \'credit_id\': \'6489aa936f8d9500afdf219c\', \'order\': 1}, {\'adult\': False, \'gender\': 2, \'id\': 3085, \'known_for_department\': \'Acting\', \'name\': \'James Caan\', \'original_name\': \'James Caan\', \'popularity\': 17.879, \'profile_path\': \'/v3flJtQEyczxENi29yJyvnN6LVt.jpg\', \'cast_id\': 148, \'character\': \'Sonny Corleone\', \'credit_id\': \'6489aabc99259c00ff111136\', \'order\': 2}, {\'adult\': False, \'gender\': 2, \'id\': 3087, \'known_for_department\': \'Acting\', \'name\': \'Robert Duvall\', \'original_name\': \'Robert Duvall\', \'popularity\': 27.185, \'profile_path\': \'/nLBIEvJDvSV0WhFv0bi7sU9tLyb.jpg\', \'cast_id\': 149, \'character\': \'Tom Hagen\', \'credit_id\': \'6489aace99259c011c42808d\', \'order\': 3}, {\'adult\': False, \'gender\': 2, \'id\': 3086, \'known_for_department\': \'Acting\', \'name\': \'Richard S. Castellano\', \'original_name\': \'Richard S. Castellano\', \'popularity\': 5.701, \'profile_path\': \'/1vr75BdHWret81vuSJ3ugiCBkxw.jpg\', \'cast_id\': 150, \'character\': \'Clemenza\', \'credit_id\': \'6489aaf86f8d9500c88bea14\', \'order\': 4}, {\'adult\': False, \'gender\': 1, \'id\': 3092, \'known_for_department\': \'Acting\', \'name\': \'Diane Keaton\', \'original_name\': \'Diane Keaton\', \'popularity\': 20.466, \'profile_path\': \'/tnx7pJqisfAzvXOR5wHQsbnH9XH.jpg\', \'cast_id\': 151, \'character\': \'Kay Adams\', \'credit_id\': \'6489ab23bf31f25055a33a46\', \'order\': 5}, {\'adult\': False, \'gender\': 1, \'id\': 3094, \'known_for_department\': \'Acting\', \'name\': \'Talia Shire\', \'original_name\': \'Talia Shire\', \'popularity\': 17.353, \'profile_path\': \'/due9MtmbvCMDd1aNveuMyjsaZ8W.jpg\', \'cast_id\': 152, \'character\': \'Connie Corleone Rizzi\', \'credit_id\': \'6489ab5799259c011c4280d8\', \'order\': 6}, {\'adult\': False, \'gender\': 2, \'id\': 3095, \'known_for_department\': \'Acting\', \'name\': \'Gianni Russo\', \'original_name\': \'Gianni Russo\', \'popularity\': 4.889, \'profile_path\': \'/5fjg2WPvuk1NvUpLyQ7aMJqOqy.jpg\', \'cast_id\': 153, \'character\': \'Carlo Rizzi\', \'credit_id\': \'6489ab77e375c00139c26e5b\', \'order\': 7}, {\'adult\': False, \'gender\': 2, \'id\': 3088, \'known_for_department\': \'Acting\', \'name\': \'Sterling Hayden\', \'original_name\': \'Sterling Hayden\', \'popularity\': 11.717, \'profile_path\': \'/dCTe6BsGSp9QTcva2Pz4wbxxYMY.jpg\', \'cast_id\': 154, \'character\': \'Captain McCluskey\', \'credit_id\': \'6489abe0d2b209014e0b8df9\', \'order\': 8}, {\'adult\': False, \'gender\': 2, \'id\': 3142, \'known_for_department\': \'Acting\', \'name\': \'John Marley\', \'original_name\': \'John Marley\', \'popularity\': 7.066, \'profile_path\': \'/k8YnXZDhhn28bSE75tLz9juR46u.jpg\', \'cast_id\': 155, \'character\': \'Jack Woltz\', \'credit_id\': \'6489ac0299259c011c42811f\', \'order\': 9}, {\'adult\': False, \'gender\': 2, \'id\': 3090, \'known_for_department\': \'Acting\', \'name\': \'Richard Conte\', \'original_name\': \'Richard Conte\', \'popularity\': 9.384, \'profile_path\': \'/bDegodf4dYGXMejdm4T6XgOJwlr.jpg\', \'cast_id\': 156, \'character\': \'Barzini\', \'credit_id\': \'6489ac126f8d9500afdf2251\', \'order\': 10}, {\'adult\': False, \'gender\': 2, \'id\': 3091, \'known_for_department\': \'Acting\', \'name\': \'Al Lettieri\', \'original_name\': \'Al Lettieri\', \'popularity\': 12.455, \'profile_path\': \'/fE5mEWPkkVJlCji0EoKht8PYw89.jpg\', \'cast_id\': 157, \'character\': \'Sollozzo\', \'credit_id\': \'6489ac20e375c000acc796d1\', \'order\': 11}, {\'adult\': False, \'gender\': 2, \'id\': 3093, \'known_for_department\': \'Acting\', \'name\': \'Abe Vigoda\', \'original_name\': \'Abe Vigoda\', \'popularity\': 8.562, \'profile_path\': \'/luWKPNb58IgJ2ovrtgPAzHGLLYL.jpg\', \'cast_id\': 158, \'character\': \'Sal Tessio\', \'credit_id\': \'6489ac2dbf31f2505708a65c\', \'order\': 12}, {\'adult\': False, \'gender\': 2, \'id\': 3096, \'known_for_department\': \'Acting\', \'name\': \'John Cazale\', \'original_name\': \'John Cazale\', \'popularity\': 9.719, \'profile_path\': \'/41wXX1FBalyIuf5eaA4S43Y8IfZ.jpg\', \'cast_id\': 159, \'character\': \'Fredo Corleone\', \'credit_id\': \'6489ac3a6f8d9500afdf2260\', \'order\': 13}, {\'adult\': False, \'gender\': 2, \'id\': 3143, \'known_for_department\': \'Acting\', \'name\': \'Rudy Bond\', \'original_name\': \'Rudy Bond\', \'popularity\': 3.379, \'profile_path\': \'/kP77m6ot9dfOR2V3ykbyOAx2diK.jpg\', \'cast_id\': 160, \'character\': \'Cuneo\', \'credit_id\': \'6489ac5de375c00139c26eb2\', \'order\': 14}, {\'adult\': False, \'gender\': 2, \'id\': 3144, \'known_for_department\': \'Acting\', \'name\': \'Al Martino\', \'original_name\': \'Al Martino\', \'popularity\': 1.682, \'profile_path\': \'/9luOyyiqWFNQgSOSStH66LTWZ3p.jpg\', \'cast_id\': 161, \'character\': \'Johnny Fontane\', \'credit_id\': \'6489ac7199259c01392da0db\', \'order\': 15}, {\'adult\': False, \'gender\': 1, \'id\': 933716, \'known_for_department\': \'Acting\', \'name\': \'Morgana King\', \'original_name\': \'Morgana King\', \'popularity\': 1.788, \'profile_path\': \'/zPsFAqH4NXD7rMWl2Kj3rEyGrKj.jpg\', \'cast_id\': 162, \'character\': \'Mama Corleone\', \'credit_id\': \'6489ac82e272600107248470\', \'order\': 16}, {\'adult\': False, \'gender\': 2, \'id\': 106811, \'known_for_department\': \'Acting\', \'name\': \'Lenny Montana\', \'original_name\': \'Lenny Montana\', \'popularity\': 6.287, \'profile_path\': \'/3R52Zh3MBCaSPqmcyWcD1Y0N4wo.jpg\', \'cast_id\': 163, \'character\': \'Luca Brasi\', \'credit_id\': \'6489ac90d2b20900ca220c08\', \'order\': 17}, {\'adult\': False, \'gender\': 2, \'id\': 99724, \'known_for_department\': \'Acting\', \'name\': \'John Martino\', \'original_name\': \'John Martino\', \'popularity\': 2.113, \'profile_path\': \'/3c8BOgJ8UdHi5x5BS3lYnFngxB5.jpg\', \'cast_id\': 164, \'character\': \'Paulie Gatto\', \'credit_id\': \'6489ac9dd2b20900ca220c0f\', \'order\': 18}, {\'adult\': False, \'gender\': 2, \'id\': 1195877, \'known_for_department\': \'Acting\', \'name\': \'Salvatore Corsitto\', \'original_name\': \'Salvatore Corsitto\', \'popularity\': 2.908, \'profile_path\': \'/79OfgwtdP5qsR1UX6ERkrdmRT8c.jpg\', \'cast_id\': 165, \'character\': \'Bonasera\', \'credit_id\': \'6489acaae375c000acc79705\', \'order\': 19}, {\'adult\': False, \'gender\': 2, \'id\': 3174, \'known_for_department\': \'Acting\', \'name\': \'Richard Bright\', \'original_name\': \'Richard Bright\', \'popularity\': 6.826, \'profile_path\': \'/b1ak2kPYUwBAYgD1yi50tz8BZ7J.jpg\', \'cast_id\': 166, \'character\': \'Neri\', \'credit_id\': \'6489acc2bf31f25054b828e4\', \'order\': 20}, {\'adult\': False, \'gender\': 2, \'id\': 20752, \'known_for_department\': \'Acting\', \'name\': \'Alex Rocco\', \'original_name\': \'Alex Rocco\', \'popularity\': 8.562, \'profile_path\': \'/uAG4qvYhYHuCyyXGm3lqC4o6ujc.jpg\', \'cast_id\': 167, \'character\': \'Moe Greene\', \'credit_id\': \'6489acd1d2b20900ad3ec8cf\', \'order\': 21}, {\'adult\': False, \'gender\': 2, \'id\': 3414, \'known_for_department\': \'Acting\', \'name\': \'Tony Giorgio\', \'original_name\': \'Tony Giorgio\', \'popularity\': 3.293, \'profile_path\': \'/1uhgwgjoX7WaakEOBmtBRJKtgEB.jpg\', \'cast_id\': 168, \'character\': \'Bruno Tattaglia\', \'credit_id\': \'6489ad08bf31f25055a33b08\', \'order\': 22}, {\'adult\': False, \'gender\': 2, \'id\': 82779, \'known_for_department\': \'Acting\', \'name\': \'Vito Scotti\', \'original_name\': \'Vito Scotti\', \'popularity\': 6.713, \'profile_path\': \'/zDGtXkASxpo3DzMNz6OI3NOp9v0.jpg\', \'cast_id\': 169, \'character\': \'Nazorine\', \'credit_id\': \'6489ad166f8d9501023e6cb2\', \'order\': 23}, {\'adult\': False, \'gender\': 1, \'id\': 982089, \'known_for_department\': \'Acting\', \'name\': \'Tere Livrano\', \'original_name\': \'Tere Livrano\', \'popularity\': 2.758, \'profile_path\': \'/eBoC3425jmwRlsT2W8qUDsNwVXB.jpg\', \'cast_id\': 170, \'character\': \'Theresa Hagen\', \'credit_id\': \'6489ad23d2b20900ad3ec8f9\', \'order\': 24}, {\'adult\': False, \'gender\': 2, \'id\': 3413, \'known_for_department\': \'Acting\', \'name\': \'Victor Rendina\', \'original_name\': \'Victor Rendina\', \'popularity\': 4.297, \'profile_path\': \'/vuNdsjDpgom80WBdB2WBTWuEIuM.jpg\', \'cast_id\': 171, \'character\': \'Philip Tattaglia\', \'credit_id\': \'6489ad306f8d9500c88beb2c\', \'order\': 25}, {\'adult\': False, \'gender\': 1, \'id\': 167363, \'known_for_department\': \'Acting\', \'name\': \'Jeannie Linero\', \'original_name\': \'Jeannie Linero\', \'popularity\': 3.837, \'profile_path\': None, \'cast_id\': 172, \'character\': \'Lucy Mancini\', \'credit_id\': \'6489ad4f6f8d95011f2439db\', \'order\': 26}, {\'adult\': False, \'gender\': 1, \'id\': 160728, \'known_for_department\': \'Acting\', \'name\': \'Julie Gregg\', \'original_name\': \'Julie Gregg\', \'popularity\': 4.319, \'profile_path\': \'/8Kx71BnZNtpzb86jH7fcArWhJBh.jpg\', \'cast_id\': 173, \'character\': \'Sandra Corleone\', \'credit_id\': \'6489ad696f8d9500c88beb4e\', \'order\': 27}, {\'adult\': False, \'gender\': 1, \'id\': 4111331, \'known_for_department\': \'Acting\', \'name\': \'Ardell Sheridan\', \'original_name\': \'Ardell Sheridan\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 174, \'character\': \'Mrs. Clemenza\', \'credit_id\': \'6489adb8bf31f25054b8295f\', \'order\': 28}, {\'adult\': False, \'gender\': 1, \'id\': 3145, \'known_for_department\': \'Acting\', \'name\': \'Simonetta Stefanelli\', \'original_name\': \'Simonetta Stefanelli\', \'popularity\': 17.724, \'profile_path\': \'/sVDrhgxuE6SHnj7q07OG6ywPUYR.jpg\', \'cast_id\': 175, \'character\': \'Apollonia - Sicilian Sequence\', \'credit_id\': \'6489ae04bf31f25055a33b87\', \'order\': 29}, {\'adult\': False, \'gender\': 2, \'id\': 27647, \'known_for_department\': \'Acting\', \'name\': \'Angelo Infanti\', \'original_name\': \'Angelo Infanti\', \'popularity\': 9.205, \'profile_path\': \'/dkRVpiDj9YyiuM15XZKT11zZBIR.jpg\', \'cast_id\': 176, \'character\': \'Fabrizio - Sicilian Sequence\', \'credit_id\': \'6489ae14d2b20900ca220cca\', \'order\': 30}, {\'adult\': False, \'gender\': 2, \'id\': 24604, \'known_for_department\': \'Acting\', \'name\': \'Corrado Gaipa\', \'original_name\': \'Corrado Gaipa\', \'popularity\': 2.192, \'profile_path\': \'/4QkQQwEhzx7kofdChg2stkIgMLe.jpg\', \'cast_id\': 177, \'character\': \'Don Tommasino - Sicilian Sequence\', \'credit_id\': \'6489ae21d2b20900ca220cd4\', \'order\': 31}, {\'adult\': False, \'gender\': 2, \'id\': 44860, \'known_for_department\': \'Acting\', \'name\': \'Franco Citti\', \'original_name\': \'Franco Citti\', \'popularity\': 4.656, \'profile_path\': \'/mttQPjOHaql4RKsfYriUA7HuROE.jpg\', \'cast_id\': 178, \'character\': \'Calo - Sicilian Sequence\', \'credit_id\': \'6489ae2e6f8d9500c88bebcf\', \'order\': 32}, {\'adult\': False, \'gender\': 2, \'id\': 119431, \'known_for_department\': \'Acting\', \'name\': \'Saro UrzÃ¬\', \'original_name\': \'Saro UrzÃ¬\', \'popularity\': 2.572, \'profile_path\': \'/wp88yz8T1TJcw5egiDu1m5a302D.jpg\', \'cast_id\': 179, \'character\': \'Vitelli - Sicilian Sequence\', \'credit_id\': \'6489ae3ce2726000afc4c253\', \'order\': 33}, {\'adult\': False, \'gender\': 2, \'id\': 38803, \'known_for_department\': \'Writing\', \'name\': \'Roman Coppola\', \'original_name\': \'Roman Coppola\', \'popularity\': 6.825, \'profile_path\': \'/rKamKkx78qjZTfvqi2OWCo5p6x5.jpg\', \'cast_id\': 182, \'character\': \'Boy on Street Who Attended Funeral (uncredited)\', \'credit_id\': \'6489af3ce2726001287c0ab0\', \'order\': 34}, {\'adult\': False, \'gender\': 1, \'id\': 1769, \'known_for_department\': \'Directing\', \'name\': \'Sofia Coppola\', \'original_name\': \'Sofia Coppola\', \'popularity\': 7.281, \'profile_path\': \'/dzHC2LxmarkBxWLhjp2DRa5oCev.jpg\', \'cast_id\': 181, \'character\': \'Michael Francis Rizzi (uncredited)\', \'credit_id\': \'6489af2de375c000acc797fe\', \'order\': 35}, {\'adult\': False, \'gender\': 0, \'id\': 1209294, \'known_for_department\': \'Acting\', \'name\': \'Don Costello\', \'original_name\': \'Don Costello\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 183, \'character\': \'Don Victor Stracci (uncredited)\', \'credit_id\': \'6489af7abf31f2505883d309\', \'order\': 36}, {\'adult\': False, \'gender\': 1, \'id\': 126072, \'known_for_department\': \'Acting\', \'name\': \'Italia Coppola\', \'original_name\': \'Italia Coppola\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 184, \'character\': \'Extra in Wedding Scene (uncredited)\', \'credit_id\': \'6489afb46f8d95011f243b21\', \'order\': 37}, {\'adult\': False, \'gender\': 2, \'id\': 2870, \'known_for_department\': \'Production\', \'name\': \'Gray Frederickson\', \'original_name\': \'Gray Frederickson\', \'popularity\': 1.396, \'profile_path\': None, \'cast_id\': 195, \'character\': "Cowboy on the Set at Woltz\'s Studio (uncredited)", \'credit_id\': \'6489b195e375c00139c270d3\', \'order\': 38}, {\'adult\': False, \'gender\': 2, \'id\': 160621, \'known_for_department\': \'Acting\', \'name\': \'Ron Gilbert\', \'original_name\': \'Ron Gilbert\', \'popularity\': 1.312, \'profile_path\': \'/qrY6w2k0YpuMB2yTCOv6cxeQtmw.jpg\', \'cast_id\': 185, \'character\': \'Usher in Bridal Party (uncredited)\', \'credit_id\': \'6489afe46f8d95013c752d10\', \'order\': 39}, {\'adult\': False, \'gender\': 2, \'id\': 1233541, \'known_for_department\': \'Acting\', \'name\': \'Sonny Grosso\', \'original_name\': \'Sonny Grosso\', \'popularity\': 2.819, \'profile_path\': None, \'cast_id\': 202, \'character\': \'Cop Outside Hospital (uncredited)\', \'credit_id\': \'6489b33fe272600107248730\', \'order\': 40}, {\'adult\': False, \'gender\': 2, \'id\': 20973, \'known_for_department\': \'Acting\', \'name\': \'Louis Guss\', \'original_name\': \'Louis Guss\', \'popularity\': 3.225, \'profile_path\': \'/hz5Akuh4QcqitlifYwDiZ9ut6Tr.jpg\', \'cast_id\': 180, \'character\': \'Don Zaluchi (uncredited)\', \'credit_id\': \'6489af11e375c000ff4ab5f2\', \'order\': 41}, {\'adult\': False, \'gender\': 2, \'id\': 1068099, \'known_for_department\': \'Acting\', \'name\': \'Randy Jurgensen\', \'original_name\': \'Randy Jurgensen\', \'popularity\': 1.333, \'profile_path\': \'/xRoN79wRLndTMCJoaBSsdjQVIzI.jpg\', \'cast_id\': 186, \'character\': "Sonny\'s Killer #1 (uncredited)", \'credit_id\': \'6489affed2b209014e0b8fdb\', \'order\': 42}, {\'adult\': False, \'gender\': 2, \'id\': 55672, \'known_for_department\': \'Acting\', \'name\': \'Tony King\', \'original_name\': \'Tony King\', \'popularity\': 3.233, \'profile_path\': \'/hOVVHEyc6euuuRhCLo6Q5YE4lLz.jpg\', \'cast_id\': 196, \'character\': \'Tony - Stablehand (uncredited)\', \'credit_id\': \'6489b214e375c000ff4ab714\', \'order\': 43}, {\'adult\': False, \'gender\': 2, \'id\': 61241, \'known_for_department\': \'Acting\', \'name\': \'Tony Lip\', \'original_name\': \'Tony Lip\', \'popularity\': 3.48, \'profile_path\': \'/6xz6XmjgiCCOm067OzWYziD4Mxa.jpg\', \'cast_id\': 206, \'character\': \'Wedding Guest (uncredited)\', \'credit_id\': \'6489b6276f8d9500e5015933\', \'order\': 44}, {\'adult\': False, \'gender\': 2, \'id\': 1503036, \'known_for_department\': \'Acting\', \'name\': \'Joe Lo Grippo\', \'original_name\': \'Joe Lo Grippo\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 188, \'character\': "Sonny\'s Bodyguard (uncredited)", \'credit_id\': \'6489b0736f8d9500afdf2448\', \'order\': 45}, {\'adult\': False, \'gender\': 2, \'id\': 106187, \'known_for_department\': \'Acting\', \'name\': \'Lou Martini Jr.\', \'original_name\': \'Lou Martini Jr.\', \'popularity\': 4.434, \'profile_path\': \'/85s5KR0BA6dhMJtOrvtKGY8Bz8E.jpg\', \'cast_id\': 187, \'character\': \'Boy at Wedding (uncredited)\', \'credit_id\': \'6489b033d2b20900ca220dd5\', \'order\': 46}, {\'adult\': False, \'gender\': 2, \'id\': 100503, \'known_for_department\': \'Acting\', \'name\': \'Raymond Martino\', \'original_name\': \'Raymond Martino\', \'popularity\': 2.241, \'profile_path\': None, \'cast_id\': 207, \'character\': \'Corleone Family Member (uncredited)\', \'credit_id\': \'6489b647e272600147bc20cf\', \'order\': 47}, {\'adult\': False, \'gender\': 2, \'id\': 1503035, \'known_for_department\': \'Acting\', \'name\': \'Joseph Medaglia\', \'original_name\': \'Joseph Medaglia\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 191, \'character\': \'Priest at Baptism (uncredited)\', \'credit_id\': \'6489b100bf31f250569dd401\', \'order\': 48}, {\'adult\': False, \'gender\': 1, \'id\': 2313192, \'known_for_department\': \'Acting\', \'name\': \'Carol Morley\', \'original_name\': \'Carol Morley\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 190, \'character\': \'Night Nurse (uncredited)\', \'credit_id\': \'6489b0cee27260010724864d\', \'order\': 49}, {\'adult\': False, \'gender\': 0, \'id\': 1290895, \'known_for_department\': \'Acting\', \'name\': \'Rick Petrucelli\', \'original_name\': \'Rick Petrucelli\', \'popularity\': 0.6, \'profile_path\': None, \'cast_id\': 189, \'character\': "Lou - Sollozzo\'s Driver (uncredited)", \'credit_id\': \'6489b09f99259c00accf128f\', \'order\': 50}, {\'adult\': False, \'gender\': 2, \'id\': 1237372, \'known_for_department\': \'Acting\', \'name\': \'Sal Richards\', \'original_name\': \'Sal Richards\', \'popularity\': 1.172, \'profile_path\': \'/gZSiZOtBVv1U4hqjlKkPr2p5rCP.jpg\', \'cast_id\': 198, \'character\': \'Drunk (uncredited)\', \'credit_id\': \'6489b2a2bf31f2505708a90f\', \'order\': 51}, {\'adult\': False, \'gender\': 2, \'id\': 1213795, \'known_for_department\': \'Acting\', \'name\': \'Tom Rosqui\', \'original_name\': \'Tom Rosqui\', \'popularity\': 3.425, \'profile_path\': None, \'cast_id\': 192, \'character\': \'Rocco Lampone (uncredited)\', \'credit_id\': \'6489b118e375c0011c8206ba\', \'order\': 52}, {\'adult\': False, \'gender\': 2, \'id\': 11480, \'known_for_department\': \'Acting\', \'name\': \'Frank Sivero\', \'original_name\': \'Frank Sivero\', \'popularity\': 5.04, \'profile_path\': \'/eqvhj0iNtcsN6EJhd21Goqi1DSq.jpg\', \'cast_id\': 199, \'character\': \'Street Extra (uncredited)\', \'credit_id\': \'6489b2f3e2726000e8c326a5\', \'order\': 53}, {\'adult\': False, \'gender\': 0, \'id\': 1209678, \'known_for_department\': \'Acting\', \'name\': \'Filomena Spagnuolo\', \'original_name\': \'Filomena Spagnuolo\', \'popularity\': 1.109, \'profile_path\': None, \'cast_id\': 200, \'character\': \'Extra in Wedding Scene (uncredited)\', \'credit_id\': \'6489b306bf31f2505f40b8be\', \'order\': 54}, {\'adult\': False, \'gender\': 2, \'id\': 16525, \'known_for_department\': \'Acting\', \'name\': \'Joe Spinell\', \'original_name\': \'Joe Spinell\', \'popularity\': 10.597, \'profile_path\': \'/jiok99ZvHDOj51BBgio2qvum0Mb.jpg\', \'cast_id\': 193, \'character\': \'Willi Cicci (uncredited)\', \'credit_id\': \'6489b12ee2726000e8c325be\', \'order\': 55}, {\'adult\': False, \'gender\': 2, \'id\': 138211, \'known_for_department\': \'Acting\', \'name\': \'Gabriele Torrei\', \'original_name\': \'Gabriele Torrei\', \'popularity\': 4.372, \'profile_path\': \'/x3KeYWTWX5SqZ3NuQGiWiadO4DI.jpg\', \'cast_id\': 197, \'character\': \'Enzo the Baker (uncredited)\', \'credit_id\': \'6489b22a99259c00e2f7628c\', \'order\': 56}, {\'adult\': False, \'gender\': 2, \'id\': 78336, \'known_for_department\': \'Directing\', \'name\': \'Nick Vallelonga\', \'original_name\': \'Nick Vallelonga\', \'popularity\': 4.695, \'profile_path\': \'/h0GwAHN1J5lDysqgWxMIg66LNBW.jpg\', \'cast_id\': 201, \'character\': \'W

In [12]:
#from the above dictionary, we need only top three cast
def convert2(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter +=1
        else:
            break
    return L

In [13]:
movies['Actors'] = movies['Actors'].apply(convert2)
movies.head()

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Marlon Brando, Al Pacino, James Caan]","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[italy, loss of loved one, love at first sight...","[Drama, Crime]"
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[Tim Robbins, Morgan Freeman, Bob Gunton]","[{'adult': False, 'gender': 2, 'id': 153, 'kno...","[prison, corruption, police brutality, based o...","[Drama, Crime]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Al Pacino, Robert Duvall, Diane Keaton]","[{'adult': False, 'gender': 2, 'id': 154, 'kno...","[italy, italian american, cuba, symbolism, gan...","[Drama, Crime]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[Liam Neeson, Ben Kingsley, Ralph Fiennes]","[{'adult': False, 'gender': 2, 'id': 491, 'kno...","[based on novel or book, factory, concentratio...","[Drama, History, War]"
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[Shah Rukh Khan, Kajol, Amrish Puri]","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...","[family's daily life, family history, love-hat...","[Comedy, Drama, Romance]"

In [14]:
#here we need only that dictionary whose job is Director, and we need to 
#extract name from that dictionary

def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [15]:
movies['crew']= movies['crew'].apply(fetch_director)
movies.head()

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Marlon Brando, Al Pacino, James Caan]",[Francis Ford Coppola],"[italy, loss of loved one, love at first sight...","[Drama, Crime]"
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[Tim Robbins, Morgan Freeman, Bob Gunton]",[Frank Darabont],"[prison, corruption, police brutality, based o...","[Drama, Crime]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Al Pacino, Robert Duvall, Diane Keaton]",[Francis Ford Coppola],"[italy, italian american, cuba, symbolism, gan...","[Drama, Crime]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[Liam Neeson, Ben Kingsley, Ralph Fiennes]",[Steven Spielberg],"[based on novel or book, factory, concentratio...","[Drama, History, War]"
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[Shah Rukh Khan, Kajol, Amrish Puri]",[Aditya Chopra],"[family's daily life, family history, love-hat...","[Comedy, Drama, Romance]"

In [16]:
movies_dataset = movies[['id','title','overview','Actors','crew','keywords','genres']]
movies_dataset

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Marlon Brando, Al Pacino, James Caan]",[Francis Ford Coppola],"[italy, loss of loved one, love at first sight...","[Drama, Crime]"
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"[Tim Robbins, Morgan Freeman, Bob Gunton]",[Frank Darabont],"[prison, corruption, police brutality, based o...","[Drama, Crime]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Al Pacino, Robert Duvall, Diane Keaton]",[Francis Ford Coppola],"[italy, italian american, cuba, symbolism, gan...","[Drama, Crime]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[Liam Neeson, Ben Kingsley, Ralph Fiennes]",[Steven Spielberg],"[based on novel or book, factory, concentratio...","[Drama, History, War]"
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[Shah Rukh Khan, Kajol, Amrish Puri]",[Aditya Chopra],"[family's daily life, family history, love-hat...","[Comedy, Drama, Romance]"
...,...,...,...,...,...,...,...
9995,124459,The Incredible Burt Wonderstone,After breaking up with his longtime stage part...,"[Steve Carell, Steve Buscemi, Olivia Wilde]",[Don Scardino],"[magic, las vegas]",[Comedy]
9996,523931,Megalodon,A military vessel on the search for an unident...,"[Michael Madsen, Scott C. Roe, Ego Mikitas]",[James Thomas],"[submarine, monster, shark attack, prehistoric...","[Action, Science Fiction, Horror, TV Movie]"
9997,265208,Wild Card,When a Las Vegas bodyguard with lethal skills ...,"[Jason Statham, Michael Angarano, Dominik Garcia]",[Simon West],"[gambling, bodyguard, remake, las vegas]","[Thriller, Crime, Action]"
9998,51170,Open Season 3,"Boog, Elliot, and their forest friends return ...","[Matthew J. Munn, Nika Futterman, Maddie Taylor]",[Cody Cameron],"[circus, friendship, deer, bear, look-alike, f...","[Adventure, Animation, Family, Comedy]"
9999,39451,Little Fockers,"It has taken 10 years, two little Fockers with...","[Robert De Niro, Ben Stiller, Owen Wilson]",[Paul Weitz],"[nurse, cat, father-in-law, vomit, viagra, ove...","[Comedy, Romance]"

In [17]:
movies_dataset.isnull().sum()

id          0
title       0
overview    2
Actors      0
crew        0
keywords    0
genres      0
dtype: int64

In [18]:
movies_dataset.dropna(inplace=True)

In [19]:
movies_dataset['overview']= movies_dataset['overview'].apply(lambda x: x.split())

In [20]:
movies_dataset['genres'] = movies_dataset['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies_dataset['keywords'] = movies_dataset['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies_dataset['Actors'] = movies_dataset['Actors'].apply(lambda x:[i.replace(" ","") for i in x])
movies_dataset['crew'] = movies_dataset['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies_dataset.head()

,id,title,overview,Actors,crew,keywords,genres
0,238,The Godfather,"[Spanning, the, years, 1945, to, 1955,, a, chr...","[MarlonBrando, AlPacino, JamesCaan]",[FrancisFordCoppola],"[italy, lossoflovedone, loveatfirstsight, base...","[Drama, Crime]"
1,278,The Shawshank Redemption,"[Framed, in, the, 1940s, for, the, double, mur...","[TimRobbins, MorganFreeman, BobGunton]",[FrankDarabont],"[prison, corruption, policebrutality, basedonn...","[Drama, Crime]"
2,240,The Godfather Part II,"[In, the, continuing, saga, of, the, Corleone,...","[AlPacino, RobertDuvall, DianeKeaton]",[FrancisFordCoppola],"[italy, italianamerican, cuba, symbolism, gang...","[Drama, Crime]"
3,424,Schindler's List,"[The, true, story, of, how, businessman, Oskar...","[LiamNeeson, BenKingsley, RalphFiennes]",[StevenSpielberg],"[basedonnovelorbook, factory, concentrationcam...","[Drama, History, War]"
4,19404,Dilwale Dulhania Le Jayenge,"[Raj, is, a, rich,, carefree,, happy-go-lucky,...","[ShahRukhKhan, Kajol, AmrishPuri]",[AdityaChopra],"[family'sdailylife, familyhistory, love-hatere...","[Comedy, Drama, Romance]"

In [21]:
# Now let's create a new column called tags in which we will concatenate
# overview, genres, keywords, cast, crew

movies_dataset['tags'] = movies_dataset['overview']+movies_dataset['genres']+movies_dataset['keywords']+movies_dataset['Actors']+movies_dataset['crew']

In [22]:
movies_dataset.head()

,id,title,overview,Actors,crew,keywords,genres,tags
0,238,The Godfather,"[Spanning, the, years, 1945, to, 1955,, a, chr...","[MarlonBrando, AlPacino, JamesCaan]",[FrancisFordCoppola],"[italy, lossoflovedone, loveatfirstsight, base...","[Drama, Crime]","[Spanning, the, years, 1945, to, 1955,, a, chr..."
1,278,The Shawshank Redemption,"[Framed, in, the, 1940s, for, the, double, mur...","[TimRobbins, MorganFreeman, BobGunton]",[FrankDarabont],"[prison, corruption, policebrutality, basedonn...","[Drama, Crime]","[Framed, in, the, 1940s, for, the, double, mur..."
2,240,The Godfather Part II,"[In, the, continuing, saga, of, the, Corleone,...","[AlPacino, RobertDuvall, DianeKeaton]",[FrancisFordCoppola],"[italy, italianamerican, cuba, symbolism, gang...","[Drama, Crime]","[In, the, continuing, saga, of, the, Corleone,..."
3,424,Schindler's List,"[The, true, story, of, how, businessman, Oskar...","[LiamNeeson, BenKingsley, RalphFiennes]",[StevenSpielberg],"[basedonnovelorbook, factory, concentrationcam...","[Drama, History, War]","[The, true, story, of, how, businessman, Oskar..."
4,19404,Dilwale Dulhania Le Jayenge,"[Raj, is, a, rich,, carefree,, happy-go-lucky,...","[ShahRukhKhan, Kajol, AmrishPuri]",[AdityaChopra],"[family'sdailylife, familyhistory, love-hatere...","[Comedy, Drama, Romance]","[Raj, is, a, rich,, carefree,, happy-go-lucky,..."

In [23]:
final = movies_dataset[['id','title','tags']]
final.head()

,id,title,tags
0,238,The Godfather,"[Spanning, the, years, 1945, to, 1955,, a, chr..."
1,278,The Shawshank Redemption,"[Framed, in, the, 1940s, for, the, double, mur..."
2,240,The Godfather Part II,"[In, the, continuing, saga, of, the, Corleone,..."
3,424,Schindler's List,"[The, true, story, of, how, businessman, Oskar..."
4,19404,Dilwale Dulhania Le Jayenge,"[Raj, is, a, rich,, carefree,, happy-go-lucky,..."

In [24]:
#convert the list of tags to string
final['tags']= final['tags'].apply(lambda x:" ".join(x))
final.head()

C:\Users\1681A\AppData\Local\Temp/ipykernel_24916/846700141.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['tags']= final['tags'].apply(lambda x:" ".join(x))

,id,title,tags
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."

In [25]:
final['tags'][0]

'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge. Drama Crime italy lossoflovedone loveatfirstsight basedonnovelorbook europe symbolism patriarch organizedcrime mafia lawyer religion revengemotive crimefamily sicilianmafia religioushypocrisy gunviolence risetopower deadhorse gangviolence 1940s 1950s mafiawar MarlonBrando AlPacino JamesCaan FrancisFordCoppola'

In [26]:
#let's convert everything in lower case

final['tags'] = final['tags'].apply(lambda x: x.lower())
final.head()

C:\Users\1681A\AppData\Local\Temp/ipykernel_24916/1378080531.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['tags'] = final['tags'].apply(lambda x: x.lower())

,id,title,tags
0,238,The Godfather,"spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,framed in the 1940s for the double murder of h...
2,240,The Godfather Part II,in the continuing saga of the corleone crime f...
3,424,Schindler's List,the true story of how businessman oskar schind...
4,19404,Dilwale Dulhania Le Jayenge,"raj is a rich, carefree, happy-go-lucky second..."

In [27]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [28]:
final['tags'] = final['tags'].apply(stem)

C:\Users\1681A\AppData\Local\Temp/ipykernel_24916/471998303.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['tags'] = final['tags'].apply(stem)

In [29]:
final['tags'][0]

'span the year 1945 to 1955, a chronicl of the fiction italian-american corleon crime family. when organ crime famili patriarch, vito corleon bare surviv an attempt on hi life, hi youngest son, michael step in to take care of the would-b killers, launch a campaign of bloodi revenge. drama crime itali lossoflovedon loveatfirstsight basedonnovelorbook europ symbol patriarch organizedcrim mafia lawyer religion revengemot crimefamili sicilianmafia religioushypocrisi gunviol risetopow deadhors gangviol 1940 1950 mafiawar marlonbrando alpacino jamescaan francisfordcoppola'

In [30]:
#we will take 5000 words out of the string(formed after combining all the tags) and 
# we will remove the stop words(like - the, is, and, or etc.)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words='english' )

vectors = cv.fit_transform(final['tags']).toarray()

In [31]:
vectors.shape

(9998, 5000)

In [32]:
cv.get_feature_names()  #these are the 5000 words we have taken

['000',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '15thcenturi',
 '16',
 '16thcenturi',
 '17',
 '17th',
 '17thcenturi',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1920s',
 '1930',
 '1936',
 '1940',
 '1943',
 '1944',
 '1945',
 '1950',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1980s',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '1stcenturi',
 '20',
 '2000',
 '2010',
 '2020',
 '2030',
 '2040',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '35',
 '39',
 '40',
 '50',
 '500',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'abort',
 'abov',
 'abroad',
 'abus',
 'abusivefath',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamdriv',
 'adamsandl',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'adversari',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airforc',
 'airplan',
 'airplanecrash',
 'airport',
 'akirakurosawa',
 'al',
 'alabama',
 'alainchabat',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholabus',
 'alecbaldwin',
 'alex',
 'alexanderskarsgÃ¥rd',
 'alfredhitchcock',
 'ali',
 'alic',
 'alice',
 'aliciavikand',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allegori',
 'alli',
 'allianc',
 'allow',
 'alma',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alpsmountain',
 'alreadi',
 'alter',
 'altern',
 'alternater',
 'alway',
 'alzheimer',
 'amanda',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'amazonrainforest',
 'ambassador',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanfootbal',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'anderson',
 'andi',
 'andrea',
 'andrew',
 'andrewgarfield',
 'android',
 'andy',
 'andygarcÃ­a',
 'andysamberg',
 'andyserki',
 'angel',
 'angela',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annetteben',
 'anni',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antiwar',
 'antoin',
 'antoinefuqua',
 'antonio',
 'antoniobandera',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'apartmentbuild',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'apocalypticfutur',
 'appar',
 'appear',
 'appoint',
 'appreci',
 'approach',
 'aquarium',
 'arab',
 'archaeologist',
 'archer',
 'architect',
 'area',
 'aren',
 'arena',
 'argentina',
 'argument',
 'ariel',
 'aris',
 'aristocrat',
 'arizona',
 'arkansa',
 'arm',
 'armi',
 'armiehamm',
 'armor',
 'armsdeal',
 'army',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrives',
 'arrog',
 'arson',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'asia',
 'asianamerican',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assassins',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asterix',
 'asteroid',
 'astronaut',
 'astronom',
 'asylum',
 'atheist',
 'athlet',
 'atlanta',
 'atomicbomb',
 'attack',
 'attempt',
 'attemptedmurd',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'audreyhepburn',
 'audreytaut',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'authorities',
 'autism',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babi',
 'baby',
 'babysitt',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimore',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbarian',
 'barbi',
 'barcelona',
 'bare',
 'bargain',
 'barn',
 'baron',
 'barri',
 'barrylevinson',
 'bars',
 'bartend',
 'bas',
 'base',
 'basebal',
 'basedonchildren',
 'basedoncom',
 'basedonfairytal',
 'basedongraphicnovel',
 'basedonmagazine',
 'basedonmanga',
 'basedonmemoirorautobiographi',
 'basedonmovi',
 'basedonmyths',
 'basedonnovelorbook',
 'basedonplayormus',
 'basedonshortfilm',
 'basedonshortstori',
 'basedontoy',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'bath',
 'bathtub',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'bdsm',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belgium',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benedictcumberbatch',
 'benefactor',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benkingsley',
 'benmendelsohn',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'betray',
 'better',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billi',
 'billion',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billywild',
 'biographi',
 'biolog',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'birthdayparti',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackandwhit',
 'blackhumor',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blind',
 'blindnessandimpairedvis',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blossom',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bomb',
 'bomber',
 'bond',
 'bone',
 'book',
 'boot',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boyfriendgirlfriendrelationship',
 'boys',
 'brad',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brash',
 'bratva',
 'brave',
 'braveri',
 'brawl',
 'brazil',
 'break',
 'breakdown',
 'breakingthefourthwal',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brian',
 'briancox',
 'briandepalma',
 'bride',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britisharmi',
 'britishempir',
 'britishmonarchi',
 'britishsecretservic',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brooklyn',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewilli',
 'bruno',
 'brutal',
 'brutalviol',
 'bryancranston',
 'bu',
 'bubbl',
 'bud',
 'buddi',
 'buddycomedi',
 'buddycop',
 'budspenc',
 'bug',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bureaucraci',
 'burglar',
 'buri',
 'burn',
 'busi',
 'business',
 'businessman',
 'bust',
 'busterkeaton',
 'butcher',
 'butler',
 'buy',
 'buzz',
 'cabaret',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'california',
 'calvin',
 'came',
 'camera',
 'cameron',
 'camerondiaz',
 'camp',
 'campaign',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'cannib',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captor',
 'captur',
 'car',
 'caraccid',
 'carbomb',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caregiv',
 'caretak',
 'careymulligan',
 'cargo',
 'carl',
 'carlo',
 'carloverdon',
 'carmechan',
 'carniv',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'cartel',
 'carter',
 'cartoon',
 'cartoonmous',
 'caryelw',
 'carygr',
 'case',
 'casey',
 'caseyaffleck',
 'caseykasem',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinezeta',
 'cathol',
 'catholic',
 'catholicchurch',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'celebr',
 'celebration',
 'cell',
 'cellar',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'changes',
 'channel',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliechaplin',
 'charliesheen',
 'charlizetheron',
 'charlott',
 'charlotterampl',
 'charm',
 'chase',
 'chat',
 'chauffeur',
 'cheat',
 'check',
 'cheer',
 'cheerlead',
 'chef',
 'chemic',
 'chess',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'childhoodfriend',
 'childhoodtrauma',
 'childkidnap',
 'childmurd',
 'childprodigi',
 'children',
 'childreninwartim',
 'chile',
 'chill',
 'china',
 'chinatown',
 'chines',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chriso',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianclavi',
 'christianfilm',
 'christianslat',
 'christin',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'chronicl',
 'church',
 'cia',
 'cigarett',
 'circl',
 'circu',
 'circumst',
 'circumstances',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'clair',
 'clan',
 'clara',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'clau',
 'claud',
 'claudevandamm',
 'claudia',
 'claudio',
 'claus',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'climb',
 'clinic',
 'clinteastwood',
 'cliqu',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'closest',
 'closet',
 'cloud',
 'clouseau',
 'clown',
 'club',
 'clue',
 'clumsi',
 'coach',
 'coast',
 'coastal',
 'cocain',
 'cod',
 'code',
 'coffe',
 'coffin',
 'cold',
 'coldwar',
 'cole',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'collar',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collegestud',
 'collid',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'com',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'comicbook',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compass',
 'compel',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'comput',
 'conartist',
 'concentr',
 'concentrationcamp',
 'concern',
 'concert',
 'condit',
 'conduct',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connection',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'consist',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contraband',
 'contract',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convert',
 ...]

In [33]:
# Eucledin distance is not a reliable measure in high dimension so we use cosine distance

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.25150891, 0.3919532 , ..., 0.08285523, 0.08723179,
        0.06378198],
       [0.25150891, 1.        , 0.07804228, ..., 0.04949222, 0.09118635,
        0.14287172],
       [0.3919532 , 0.07804228, 1.        , ..., 0.10283868, 0.09022567,
        0.        ],
       ...,
       [0.08285523, 0.04949222, 0.10283868, ..., 1.        , 0.        ,
        0.02510219],
       [0.08723179, 0.09118635, 0.09022567, ..., 0.        , 1.        ,
        0.06607032],
       [0.06378198, 0.14287172, 0.        , ..., 0.02510219, 0.06607032,
        1.        ]])

In [34]:
similarity.shape #cosine distance of every movie with every movies

(9998, 9998)

In [35]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

#if we just sort the similarity vector then we will lose the index i.e. which 
# distance is related to which movie, but when we use the enumerate then we get
# index as well as distance. Now we sort in descending order(reverse=True) and
# on the basis of second index (key=lambda x:x[1])
# [1:6] gives the first value to 6th value i.e. 5 values total

[(2, 0.39195320067840805),
 (1747, 0.3595159254890833),
 (6377, 0.31974732916313325),
 (9633, 0.31801759529697826),
 (1869, 0.3141404312187716)]

In [36]:
#the diagonal values of the above matrix will be 1 because the similarity of every
# movie with itself is 1

#now we will make a function which we take a movie from me and recommend top 5
#movies with maximum similarity to the given movie.

#for that we are making this function which will first of all find the index of the giveb
#movie in the dataset and from the index it will get the similarity vector and
# then sort that vector in descending order and return top 5

def recommend(movie):
    movie_index = final[final['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(final.iloc[i[0]].title)

In [37]:
recommend('The Lord of the Rings: The Two Towers')

The Hobbit: The Desolation of Smaug
The Lord of the Rings: The Return of the King
The Lord of the Rings: The Fellowship of the Ring
The Lord of the Rings
The Hobbit: The Battle of the Five Armies

In [45]:
final['title'][1:60]

1                              The Shawshank Redemption
2                                 The Godfather Part II
3                                      Schindler's List
4                           Dilwale Dulhania Le Jayenge
5                                         Spirited Away
6                                          12 Angry Men
7                                            Your Name.
8                                              Parasite
9                                       The Dark Knight
10                                       The Green Mile
11                                         Pulp Fiction
12                                         Forrest Gump
13        The Lord of the Rings: The Return of the King
14                       The Good, the Bad and the Ugly
15                                           GoodFellas
16                                      Cinema Paradiso
17                                        Seven Samurai
18                                    Life Is Beautiful
19                               Grave of the Fireflies
20                                    Gabriel's Inferno
21                                     Cuando Sea Joven
22                  Spider-Man: Across the Spider-Verse
23                                               Psycho
24                                           Fight Club
25                                    The Legend of Hei
26                             Dou kyu sei â€“ Classmates
27                          Once Upon a Time in America
28                            Primal: Tales of Savagery
29                           Gabriel's Inferno: Part II
30                                    Impossible Things
31                                          City of God
32                                             Harakiri
33                      One Flew Over the Cuckoo's Nest
34                          Gabriel's Inferno: Part III
35                                         Interstellar
36                 The Quintessential Quintuplets Movie
37                    Spider-Man: Into the Spider-Verse
38                                 Howl's Moving Castle
39    The Lord of the Rings: The Fellowship of the Ring
40                            A Silent Voice: The Movie
41                                         A Dog's Will
42                              The Empire Strikes Back
43                                                 Hope
44                Taylor Swift: Reputation Stadium Tour
45                The Lord of the Rings: The Two Towers
46                                          The Pianist
47                                             Whiplash
48                                   Hotarubi no Mori e
49             The Boy, the Mole, the Fox and the Horse
50                                                Se7en
51                                            Inception
52                                          Rear Window
53                                     Sunset Boulevard
54                                   American History X
55       Neon Genesis Evangelion: The End of Evangelion
56                                         High and Low
57                        Josee, the Tiger and the Fish
58                                                Ikiru
59                             The Silence of the Lambs
Name: title, dtype: object

In [39]:
recommend('The Godfather Part II')

The Godfather Part III
The Godfather
Suburra
Dead Man Down
Street Flow

In [40]:
recommend('The Batman')

The Raid 2
The Dark Knight Rises
Batman: Mask of the Phantasm
Memoir of a Murderer
In the Shadow of the Moon

In [41]:
recommend('Spider-Man: Across the Spider-Verse')

Spider-Man: Into the Spider-Verse
Spider-Man 3
Spider-Man
Arachnophobia
Superman vs. The Elite

In [42]:
recommend('The Silence of the Lambs')

Red Dragon
The Collini Case
Resurrection
Mr. Brooks
I Saw the Devil

In [43]:
recommend('Dead Poets Society')

In the House
The Class
Notes on a Scandal
Miss Stevens
Cracks

In [46]:
recommend('Parasite')

The Host
To All the Boys: Always and Forever
Welcome to the Hartmanns
Train to Busan
Peninsula

In [47]:
recommend('Your Name.')

I Want to Eat Your Pancreas
XOXO
Rascal Does Not Dream of a Dreaming Girl
Hello World
On Body and Soul

In [48]:
recommend('Whiplash')

Mo' Better Blues
Selena
Let It Shine
New York, New York
Amadeus

In [49]:
recommend('Tron')

Free Guy
TRON: Legacy
Nirvana
Grandma's Boy
Ready Player One

In [50]:
recommend('Godzilla')

Godzilla, King of the Monsters!
Godzilla Raids Again
Mothra vs. Godzilla
King Kong vs. Godzilla
Shin Godzilla

In [52]:
recommend('The Shawshank Redemption')

Starred Up
American Me
A Prayer Before Dawn
S.W.A.T.: Under Siege
Pusher II

In [53]:
recommend('Edge of Tomorrow')

Parasyte: Part 1
The 5th Wave
Rakka
Invasion
Universal Soldier

In [54]:
recommend('Titanic')

The Legend of 1900
Standing Tall
My First Time
A Night to Remember
Life in a Year

In [55]:
recommend('Tenet')

Vanguard
Central Intelligence
The World Is Not Enough
Ava
Skyscraper

In [56]:
recommend('Interstellar')

Silent Running
Mission to Mars
Salyut-7
Lightyear
Automata

In [58]:
recommend('The Martian')

Apollo 13
The Shipping News
Cast Away
Armageddon
The Astronaut Farmer